// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: auth/v1/service.proto

package authv1

import (
	_ "github.com/twin-te/twin-te/back/handler/api/v4/rpcgen/sharedpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_auth_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_service_proto_rawDescGZIP(), []int{0}
}

type GetMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_auth_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetMeResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserAuthenticationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      Provider               `protobuf:"varint,1,opt,name=provider,proto3,enum=auth.v1.Provider" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserAuthenticationRequest) Reset() {
	*x = DeleteUserAuthenticationRequest{}
	mi := &file_auth_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserAuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserAuthenticationRequest) ProtoMessage() {}

func (x *DeleteUserAuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserAuthenticationRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserAuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteUserAuthenticationRequest) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

type DeleteUserAuthenticationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserAuthenticationResponse) Reset() {
	*x = DeleteUserAuthenticationResponse{}
	mi := &file_auth_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserAuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserAuthenticationResponse) ProtoMessage() {}

func (x *DeleteUserAuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserAuthenticationResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserAuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_service_proto_rawDescGZIP(), []int{3}
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_auth_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_service_proto_rawDescGZIP(), []int{4}
}

type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_auth_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_service_proto_rawDescGZIP(), []int{5}
}

var File_auth_v1_service_proto protoreflect.FileDescriptor

const file_auth_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15auth/v1/service.proto\x12\aauth.v1\x1a\x12auth/v1/type.proto\x1a\x13shared/option.proto\"\x0e\n" +
	"\fGetMeRequest\"2\n" +
	"\rGetMeResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.auth.v1.UserR\x04user\"P\n" +
	"\x1fDeleteUserAuthenticationRequest\x12-\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x11.auth.v1.ProviderR\bprovider\"\"\n" +
	" DeleteUserAuthenticationResponse\"\x16\n" +
	"\x14DeleteAccountRequest\"\x17\n" +
	"\x15DeleteAccountResponse2\xc8\x02\n" +
	"\vAuthService\x12A\n" +
	"\x05GetMe\x12\x15.auth.v1.GetMeRequest\x1a\x16.auth.v1.GetMeResponse\"\t\x82\xb5\x18\x02\b\x03\x90\x02\x01\x12\x9d\x01\n" +
	"\x18DeleteUserAuthentication\x12(.auth.v1.DeleteUserAuthenticationRequest\x1a).auth.v1.DeleteUserAuthenticationResponse\",\x82\xb5\x18(\b\x03\x12$auth.UserHasAtLeastOneAuthentication\x12V\n" +
	"\rDeleteAccount\x12\x1d.auth.v1.DeleteAccountRequest\x1a\x1e.auth.v1.DeleteAccountResponse\"\x06\x82\xb5\x18\x02\b\x03B^\n" +
	"\x16net.twinte.api.auth.v1ZDgithub.com/twin-te/twin-te/back/handler/api/v4/rpcgen/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_service_proto_rawDescOnce sync.Once
	file_auth_v1_service_proto_rawDescData []byte
)

func file_auth_v1_service_proto_rawDescGZIP() []byte {
	file_auth_v1_service_proto_rawDescOnce.Do(func() {
		file_auth_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_service_proto_rawDesc), len(file_auth_v1_service_proto_rawDesc)))
	})
	return file_auth_v1_service_proto_rawDescData
}

var file_auth_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_auth_v1_service_proto_goTypes = []any{
	(*GetMeRequest)(nil),                     // 0: auth.v1.GetMeRequest
	(*GetMeResponse)(nil),                    // 1: auth.v1.GetMeResponse
	(*DeleteUserAuthenticationRequest)(nil),  // 2: auth.v1.DeleteUserAuthenticationRequest
	(*DeleteUserAuthenticationResponse)(nil), // 3: auth.v1.DeleteUserAuthenticationResponse
	(*DeleteAccountRequest)(nil),             // 4: auth.v1.DeleteAccountRequest
	(*DeleteAccountResponse)(nil),            // 5: auth.v1.DeleteAccountResponse
	(*User)(nil),                             // 6: auth.v1.User
	(Provider)(0),                            // 7: auth.v1.Provider
}
var file_auth_v1_service_proto_depIdxs = []int32{
	6, // 0: auth.v1.GetMeResponse.user:type_name -> auth.v1.User
	7, // 1: auth.v1.DeleteUserAuthenticationRequest.provider:type_name -> auth.v1.Provider
	0, // 2: auth.v1.AuthService.GetMe:input_type -> auth.v1.GetMeRequest
	2, // 3: auth.v1.AuthService.DeleteUserAuthentication:input_type -> auth.v1.DeleteUserAuthenticationRequest
	4, // 4: auth.v1.AuthService.DeleteAccount:input_type -> auth.v1.DeleteAccountRequest
	1, // 5: auth.v1.AuthService.GetMe:output_type -> auth.v1.GetMeResponse
	3, // 6: auth.v1.AuthService.DeleteUserAuthentication:output_type -> auth.v1.DeleteUserAuthenticationResponse
	5, // 7: auth.v1.AuthService.DeleteAccount:output_type -> auth.v1.DeleteAccountResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_v1_service_proto_init() }
func file_auth_v1_service_proto_init() {
	if File_auth_v1_service_proto != nil {
		return
	}
	file_auth_v1_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_service_proto_rawDesc), len(file_auth_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_service_proto_goTypes,
		DependencyIndexes: file_auth_v1_service_proto_depIdxs,
		MessageInfos:      file_auth_v1_service_proto_msgTypes,
	}.Build()
	File_auth_v1_service_proto = out.File
	file_auth_v1_service_proto_goTypes = nil
	file_auth_v1_service_proto_depIdxs = nil
}
