// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: auth/v1/type.proto

package authv1

import (
	sharedpb "github.com/twin-te/twin-te/back/handler/api/v4/rpcgen/sharedpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Provider int32

const (
	Provider_PROVIDER_UNSPECIFIED Provider = 0
	Provider_PROVIDER_GOOGLE      Provider = 1
	Provider_PROVIDER_APPLE       Provider = 2
	Provider_PROVIDER_TWITTER     Provider = 3
)

// Enum value maps for Provider.
var (
	Provider_name = map[int32]string{
		0: "PROVIDER_UNSPECIFIED",
		1: "PROVIDER_GOOGLE",
		2: "PROVIDER_APPLE",
		3: "PROVIDER_TWITTER",
	}
	Provider_value = map[string]int32{
		"PROVIDER_UNSPECIFIED": 0,
		"PROVIDER_GOOGLE":      1,
		"PROVIDER_APPLE":       2,
		"PROVIDER_TWITTER":     3,
	}
)

func (x Provider) Enum() *Provider {
	p := new(Provider)
	*p = x
	return p
}

func (x Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_type_proto_enumTypes[0].Descriptor()
}

func (Provider) Type() protoreflect.EnumType {
	return &file_auth_v1_type_proto_enumTypes[0]
}

func (x Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provider.Descriptor instead.
func (Provider) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_type_proto_rawDescGZIP(), []int{0}
}

type UserAuthentication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      Provider               `protobuf:"varint,1,opt,name=provider,proto3,enum=auth.v1.Provider" json:"provider,omitempty"`
	SocialId      string                 `protobuf:"bytes,2,opt,name=social_id,json=socialId,proto3" json:"social_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthentication) Reset() {
	*x = UserAuthentication{}
	mi := &file_auth_v1_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthentication) ProtoMessage() {}

func (x *UserAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthentication.ProtoReflect.Descriptor instead.
func (*UserAuthentication) Descriptor() ([]byte, []int) {
	return file_auth_v1_type_proto_rawDescGZIP(), []int{0}
}

func (x *UserAuthentication) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *UserAuthentication) GetSocialId() string {
	if x != nil {
		return x.SocialId
	}
	return ""
}

type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              *sharedpb.UUID         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Authentications []*UserAuthentication  `protobuf:"bytes,2,rep,name=authentications,proto3" json:"authentications,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_auth_v1_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_auth_v1_type_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() *sharedpb.UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *User) GetAuthentications() []*UserAuthentication {
	if x != nil {
		return x.Authentications
	}
	return nil
}

var File_auth_v1_type_proto protoreflect.FileDescriptor

const file_auth_v1_type_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/type.proto\x12\aauth.v1\x1a\x11shared/type.proto\"`\n" +
	"\x12UserAuthentication\x12-\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x11.auth.v1.ProviderR\bprovider\x12\x1b\n" +
	"\tsocial_id\x18\x02 \x01(\tR\bsocialId\"k\n" +
	"\x04User\x12\x1c\n" +
	"\x02id\x18\x01 \x01(\v2\f.shared.UUIDR\x02id\x12E\n" +
	"\x0fauthentications\x18\x02 \x03(\v2\x1b.auth.v1.UserAuthenticationR\x0fauthentications*c\n" +
	"\bProvider\x12\x18\n" +
	"\x14PROVIDER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPROVIDER_GOOGLE\x10\x01\x12\x12\n" +
	"\x0ePROVIDER_APPLE\x10\x02\x12\x14\n" +
	"\x10PROVIDER_TWITTER\x10\x03B^\n" +
	"\x16net.twinte.api.auth.v1ZDgithub.com/twin-te/twin-te/back/handler/api/v4/rpcgen/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_type_proto_rawDescOnce sync.Once
	file_auth_v1_type_proto_rawDescData []byte
)

func file_auth_v1_type_proto_rawDescGZIP() []byte {
	file_auth_v1_type_proto_rawDescOnce.Do(func() {
		file_auth_v1_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_type_proto_rawDesc), len(file_auth_v1_type_proto_rawDesc)))
	})
	return file_auth_v1_type_proto_rawDescData
}

var file_auth_v1_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_v1_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_v1_type_proto_goTypes = []any{
	(Provider)(0),              // 0: auth.v1.Provider
	(*UserAuthentication)(nil), // 1: auth.v1.UserAuthentication
	(*User)(nil),               // 2: auth.v1.User
	(*sharedpb.UUID)(nil),      // 3: shared.UUID
}
var file_auth_v1_type_proto_depIdxs = []int32{
	0, // 0: auth.v1.UserAuthentication.provider:type_name -> auth.v1.Provider
	3, // 1: auth.v1.User.id:type_name -> shared.UUID
	1, // 2: auth.v1.User.authentications:type_name -> auth.v1.UserAuthentication
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_auth_v1_type_proto_init() }
func file_auth_v1_type_proto_init() {
	if File_auth_v1_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_type_proto_rawDesc), len(file_auth_v1_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_v1_type_proto_goTypes,
		DependencyIndexes: file_auth_v1_type_proto_depIdxs,
		EnumInfos:         file_auth_v1_type_proto_enumTypes,
		MessageInfos:      file_auth_v1_type_proto_msgTypes,
	}.Build()
	File_auth_v1_type_proto = out.File
	file_auth_v1_type_proto_goTypes = nil
	file_auth_v1_type_proto_depIdxs = nil
}
