apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: front
  labels:
    app.kubernetes.io/name: front
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: front
  template:
    metadata:
      labels:
        app.kubernetes.io/name: front
    spec:
      containers:
      - name: nginx
        image: ghcr.io/twin-te/twinte-front:main
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet:
            port: 80
