apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: front
  labels:
    app.kubernetes.io/name: front
spec:
  selector:
    app.kubernetes.io/name: front
  ports:
  - name: http
    port: 80
