// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: unified/v1/service.proto

package unifiedv1

import (
	v1 "github.com/twin-te/twin-te/back/handler/api/v4/rpcgen/schoolcalendar/v1"
	sharedpb "github.com/twin-te/twin-te/back/handler/api/v4/rpcgen/sharedpb"
	v11 "github.com/twin-te/twin-te/back/handler/api/v4/rpcgen/timetable/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetByDateRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Date          *sharedpb.RFC3339FullDate `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByDateRequest) Reset() {
	*x = GetByDateRequest{}
	mi := &file_unified_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByDateRequest) ProtoMessage() {}

func (x *GetByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unified_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByDateRequest.ProtoReflect.Descriptor instead.
func (*GetByDateRequest) Descriptor() ([]byte, []int) {
	return file_unified_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetByDateRequest) GetDate() *sharedpb.RFC3339FullDate {
	if x != nil {
		return x.Date
	}
	return nil
}

type GetByDateResponse struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Events            []*v1.Event             `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Module            v1.Module               `protobuf:"varint,2,opt,name=module,proto3,enum=schoolcalendar.v1.Module" json:"module,omitempty"`
	RegisteredCourses []*v11.RegisteredCourse `protobuf:"bytes,3,rep,name=registered_courses,json=registeredCourses,proto3" json:"registered_courses,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetByDateResponse) Reset() {
	*x = GetByDateResponse{}
	mi := &file_unified_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByDateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByDateResponse) ProtoMessage() {}

func (x *GetByDateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unified_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByDateResponse.ProtoReflect.Descriptor instead.
func (*GetByDateResponse) Descriptor() ([]byte, []int) {
	return file_unified_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetByDateResponse) GetEvents() []*v1.Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetByDateResponse) GetModule() v1.Module {
	if x != nil {
		return x.Module
	}
	return v1.Module(0)
}

func (x *GetByDateResponse) GetRegisteredCourses() []*v11.RegisteredCourse {
	if x != nil {
		return x.RegisteredCourses
	}
	return nil
}

var File_unified_v1_service_proto protoreflect.FileDescriptor

const file_unified_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18unified/v1/service.proto\x12\n" +
	"unified.v1\x1a\x1cschoolcalendar/v1/type.proto\x1a\x13shared/option.proto\x1a\x11shared/type.proto\x1a\x17timetable/v1/type.proto\"?\n" +
	"\x10GetByDateRequest\x12+\n" +
	"\x04date\x18\x01 \x01(\v2\x17.shared.RFC3339FullDateR\x04date\"\xc7\x01\n" +
	"\x11GetByDateResponse\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.schoolcalendar.v1.EventR\x06events\x121\n" +
	"\x06module\x18\x02 \x01(\x0e2\x19.schoolcalendar.v1.ModuleR\x06module\x12M\n" +
	"\x12registered_courses\x18\x03 \x03(\v2\x1e.timetable.v1.RegisteredCourseR\x11registeredCourses2\x84\x01\n" +
	"\x0eUnifiedService\x12r\n" +
	"\tGetByDate\x12\x1c.unified.v1.GetByDateRequest\x1a\x1d.unified.v1.GetByDateResponse\"(\x82\xb5\x18!\b\x03\x12\x1dschoolcalendar.ModuleNotFound\x90\x02\x01Bg\n" +
	"\x19net.twinte.api.unified.v1ZJgithub.com/twin-te/twin-te/back/handler/api/v4/rpcgen/unified/v1;unifiedv1b\x06proto3"

var (
	file_unified_v1_service_proto_rawDescOnce sync.Once
	file_unified_v1_service_proto_rawDescData []byte
)

func file_unified_v1_service_proto_rawDescGZIP() []byte {
	file_unified_v1_service_proto_rawDescOnce.Do(func() {
		file_unified_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_unified_v1_service_proto_rawDesc), len(file_unified_v1_service_proto_rawDesc)))
	})
	return file_unified_v1_service_proto_rawDescData
}

var file_unified_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_unified_v1_service_proto_goTypes = []any{
	(*GetByDateRequest)(nil),         // 0: unified.v1.GetByDateRequest
	(*GetByDateResponse)(nil),        // 1: unified.v1.GetByDateResponse
	(*sharedpb.RFC3339FullDate)(nil), // 2: shared.RFC3339FullDate
	(*v1.Event)(nil),                 // 3: schoolcalendar.v1.Event
	(v1.Module)(0),                   // 4: schoolcalendar.v1.Module
	(*v11.RegisteredCourse)(nil),     // 5: timetable.v1.RegisteredCourse
}
var file_unified_v1_service_proto_depIdxs = []int32{
	2, // 0: unified.v1.GetByDateRequest.date:type_name -> shared.RFC3339FullDate
	3, // 1: unified.v1.GetByDateResponse.events:type_name -> schoolcalendar.v1.Event
	4, // 2: unified.v1.GetByDateResponse.module:type_name -> schoolcalendar.v1.Module
	5, // 3: unified.v1.GetByDateResponse.registered_courses:type_name -> timetable.v1.RegisteredCourse
	0, // 4: unified.v1.UnifiedService.GetByDate:input_type -> unified.v1.GetByDateRequest
	1, // 5: unified.v1.UnifiedService.GetByDate:output_type -> unified.v1.GetByDateResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_unified_v1_service_proto_init() }
func file_unified_v1_service_proto_init() {
	if File_unified_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_unified_v1_service_proto_rawDesc), len(file_unified_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_unified_v1_service_proto_goTypes,
		DependencyIndexes: file_unified_v1_service_proto_depIdxs,
		MessageInfos:      file_unified_v1_service_proto_msgTypes,
	}.Build()
	File_unified_v1_service_proto = out.File
	file_unified_v1_service_proto_goTypes = nil
	file_unified_v1_service_proto_depIdxs = nil
}
