// Code generated by codegen/error/generate.py; DO NOT EDIT.

package autherr

import "github.com/twin-te/twin-te/back/apperr"

const (
	CodeUserAuthenticationAlreadyExists                apperr.Code = "auth.UserAuthenticationAlreadyExists"
	CodeUserHasAtLeastOneAuthentication                apperr.Code = "auth.UserHasAtLeastOneAuthentication"
	CodeUserHasAtMostOneAuthenticationFromSameProvider apperr.Code = "auth.UserHasAtMostOneAuthenticationFromSameProvider"
)
