
services:
  back:
    hostname: back
    ports:
      - "8080:8080"
      - "2345:2345"
    depends_on:
      - db
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
  
  front:
    hostname: front
    depends_on:
      - back
  
  sponsorship:
    depends_on:
      - back

  proxy-docker:
    depends_on:
      - back
      - front
      - sponsorship
