name: twinte-local

services:
  back:
    container_name: twinte-back
    hostname: back
    image: twinte-back-local
    build:
      context: ./back
      dockerfile: Dockerfile
      target: local
    env_file:
      - ./back/.env.local
    volumes:
      - .:/usr/src/twin-te
    ports:
      - "8080:8080"
      - "2345:2345"
    networks:
      - twinte-network
    depends_on:
      - db
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    profiles:
      - docker

  front:
    container_name: twinte-front
    hostname: front
    image: twinte-front-local
    build:
      context: ./front
      dockerfile: Dockerfile
      target: local
    volumes:
      - .:/usr/src/twin-te
      - /usr/src/twin-te/front/node_modules
    networks:
      - twinte-network
    depends_on:
      - back
    profiles:
      - docker

  sponsorship:
    container_name: twinte-sponsorship
    image: twinte-sponsorship-local
    build:
      context: ./sponsorship
      dockerfile: Dockerfile
      target: local
    volumes:
      - .:/usr/src/twin-te
      - /usr/src/twin-te/sponsorship/node_modules
      - /usr/src/twin-te/sponsorship/.next
    networks:
      - twinte-network
    depends_on:
      - back
    profiles:
      - docker

  proxy-docker:
    container_name: twinte-proxy-docker
    image: nginx
    volumes:
      - ./proxy/nginx.docker.conf:/etc/nginx/nginx.conf
    ports:
      - 4000:80
    networks:
      - twinte-network
    depends_on:
      - back
      - front
      - sponsorship
      - db
    profiles:
      - docker

  proxy-host:
    container_name: twinte-proxy-host
    image: nginx
    volumes:
      - ./proxy/nginx.host.conf:/etc/nginx/nginx.conf
    ports:
      - 4000:80
    networks:
      - twinte-network
    depends_on:
      - db
    profiles:
      - host

  db:
    container_name: twinte-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - twinte-network
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U "$POSTGRES_USER"']
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - docker
      - host

  db-migration:
    container_name: twinte-db-migration
    image: twinte-db-migration
    build:
      context: ./db
      dockerfile: Dockerfile
      target: migration
    env_file:
      - ./db/.env
    volumes:
      - ./db:/usr/src/twin-te/db
    networks:
      - twinte-network
    depends_on:
      db:
        condition: service_healthy
    profiles: []

  parser:
    container_name: twinte-parser
    image: twinte-parser
    build:
      context: ./parser
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/twin-te
    networks:
      - twinte-network
    profiles: []

  codegen:
    container_name: twinte-codegen
    image: twinte-codegen
    build:
      context: ./codegen
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/twin-te
    networks:
      - twinte-network
    profiles: []

networks:
  twinte-network:
    name: twinte-network
    driver: bridge

volumes:
  postgres_data: