name: twinte-local

services:
  back:
    container_name: twinte-back
    image: twinte-back-local
    build:
      context: ./back
      dockerfile: Dockerfile
      target: local
    env_file:
      - ./back/.env.local
    volumes:
      - .:/usr/src/twin-te
    networks:
      - twinte-network
    depends_on:
      - db

  front:
    container_name: twinte-front
    image: twinte-front-local
    build:
      context: ./front
      dockerfile: Dockerfile
      target: local
    volumes:
      - .:/usr/src/twin-te
      - /usr/src/twin-te/front/node_modules
    networks:
      - twinte-network

  sponsorship:
    container_name: twinte-sponsorship
    image: twinte-sponsorship-local
    build:
      context: ./sponsorship
      dockerfile: Dockerfile
      target: local
    volumes:
      - .:/usr/src/twin-te
      - /usr/src/twin-te/sponsorship/node_modules
      - /usr/src/twin-te/sponsorship/.next
    networks:
      - twinte-network

  proxy-docker:
    container_name: twinte-proxy-docker
    image: nginx
    volumes:
      - ./proxy/nginx.docker.conf:/etc/nginx/nginx.conf
    ports:
      - 4000:80
    networks:
      - twinte-network
    depends_on:
      - back
      - front
      - sponsorship
      - db

  proxy-host:
    container_name: twinte-proxy-host
    image: nginx
    volumes:
      - ./proxy/nginx.host.conf:/etc/nginx/nginx.conf
    ports:
      - 4000:80
    networks:
      - twinte-network
    depends_on:
      - db

  db:
    container_name: twinte-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - twinte-network     

  db-migration:
    container_name: twinte-db-migration
    image: twinte-db-migration
    build:
      context: ./db
      dockerfile: Dockerfile
      target: migration
    env_file:
      - ./db/.env
    volumes:
      - ./db:/usr/src/twin-te/db
    networks:
      - twinte-network
    depends_on:
      - db

  parser:
    container_name: twinte-parser
    image: twinte-parser
    build:
      context: ./parser
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/twin-te
    networks:
      - twinte-network

  codegen:
    container_name: twinte-codegen
    image: twinte-codegen
    build:
      context: ./codegen
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/twin-te
    networks:
      - twinte-network      

networks:
  twinte-network:
    name: twinte-network
    driver: bridge
