
services:
  back:
    depends_on:
      - db
  
  front:
    depends_on:
      - back
  
  sponsorship:
    depends_on:
      - back

  proxy-docker:
    depends_on:
      - back
      - front
      - sponsorship
    
