// Code generated by codegen/error/generate.py; DO NOT EDIT.

package interceptor

import (
	"github.com/bufbuild/connect-go"
	"github.com/twin-te/twin-te/back/apperr"
	announcementerr "github.com/twin-te/twin-te/back/module/announcement/err"
	autherr "github.com/twin-te/twin-te/back/module/auth/err"
	donationerr "github.com/twin-te/twin-te/back/module/donation/err"
	schoolcalendarerr "github.com/twin-te/twin-te/back/module/schoolcalendar/err"
	sharederr "github.com/twin-te/twin-te/back/module/shared/err"
	timetableerr "github.com/twin-te/twin-te/back/module/timetable/err"
)

var AppErrorCodeToConnectErrorCode = map[apperr.Code]connect.Code{
	announcementerr.CodeAnnouncementNotFound: connect.CodeNotFound,

	autherr.CodeUserAuthenticationAlreadyExists:                connect.CodeAlreadyExists,
	autherr.CodeUserHasAtLeastOneAuthentication:                connect.CodeFailedPrecondition,
	autherr.CodeUserHasAtMostOneAuthenticationFromSameProvider: connect.CodeFailedPrecondition,

	donationerr.CodeActiveSubscriptionAlreadyExists: connect.CodeAlreadyExists,
	donationerr.CodeSubscriptionNotFound:            connect.CodeNotFound,
	donationerr.CodeSubscriptionPlanNotFound:        connect.CodeNotFound,

	schoolcalendarerr.CodeModuleNotFound: connect.CodeNotFound,

	sharederr.CodeInvalidArgument: connect.CodeInvalidArgument,
	sharederr.CodeUnauthenticated: connect.CodeUnauthenticated,
	sharederr.CodeUnauthorized:    connect.CodePermissionDenied,

	timetableerr.CodeCourseNotFound:                connect.CodeNotFound,
	timetableerr.CodeRegisteredCourseAlreadyExists: connect.CodeAlreadyExists,
	timetableerr.CodeRegisteredCourseNotFound:      connect.CodeNotFound,
	timetableerr.CodeTagNotFound:                   connect.CodeNotFound,
}
