ruff:
	ruff format .
	ruff check --fix .

.PHONY:	idtype
idtype:
	python idtype/generate.py

.PHONY:	error
error:
	python error/generate.py

.PHONY:	schoolcalendar
schoolcalendar:
	python schoolcalendar/generate.py
