// Code generated by codegen/error/generate.py; DO NOT EDIT.

package announcementerr

import "github.com/twin-te/twin-te/back/apperr"

const (
	CodeAnnouncementNotFound apperr.Code = "announcement.AnnouncementNotFound"
)
