// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: donation/v1/service.proto

package donationv1

import (
	sharedpb "github.com/twin-te/twin-te/back/handler/api/v4/rpcgen/sharedpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOneTimeCheckoutSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOneTimeCheckoutSessionRequest) Reset() {
	*x = CreateOneTimeCheckoutSessionRequest{}
	mi := &file_donation_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOneTimeCheckoutSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOneTimeCheckoutSessionRequest) ProtoMessage() {}

func (x *CreateOneTimeCheckoutSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOneTimeCheckoutSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateOneTimeCheckoutSessionRequest) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOneTimeCheckoutSessionRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateOneTimeCheckoutSessionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CheckoutSessionId string                 `protobuf:"bytes,1,opt,name=checkout_session_id,json=checkoutSessionId,proto3" json:"checkout_session_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateOneTimeCheckoutSessionResponse) Reset() {
	*x = CreateOneTimeCheckoutSessionResponse{}
	mi := &file_donation_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOneTimeCheckoutSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOneTimeCheckoutSessionResponse) ProtoMessage() {}

func (x *CreateOneTimeCheckoutSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOneTimeCheckoutSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateOneTimeCheckoutSessionResponse) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOneTimeCheckoutSessionResponse) GetCheckoutSessionId() string {
	if x != nil {
		return x.CheckoutSessionId
	}
	return ""
}

type CreateSubscriptionCheckoutSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionCheckoutSessionRequest) Reset() {
	*x = CreateSubscriptionCheckoutSessionRequest{}
	mi := &file_donation_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionCheckoutSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionCheckoutSessionRequest) ProtoMessage() {}

func (x *CreateSubscriptionCheckoutSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionCheckoutSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionCheckoutSessionRequest) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSubscriptionCheckoutSessionRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

type CreateSubscriptionCheckoutSessionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CheckoutSessionId string                 `protobuf:"bytes,1,opt,name=checkout_session_id,json=checkoutSessionId,proto3" json:"checkout_session_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateSubscriptionCheckoutSessionResponse) Reset() {
	*x = CreateSubscriptionCheckoutSessionResponse{}
	mi := &file_donation_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionCheckoutSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionCheckoutSessionResponse) ProtoMessage() {}

func (x *CreateSubscriptionCheckoutSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionCheckoutSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionCheckoutSessionResponse) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSubscriptionCheckoutSessionResponse) GetCheckoutSessionId() string {
	if x != nil {
		return x.CheckoutSessionId
	}
	return ""
}

type GetPaymentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentUserRequest) Reset() {
	*x = GetPaymentUserRequest{}
	mi := &file_donation_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentUserRequest) ProtoMessage() {}

func (x *GetPaymentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentUserRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentUserRequest) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{4}
}

type GetPaymentUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentUser   *PaymentUser           `protobuf:"bytes,1,opt,name=payment_user,json=paymentUser,proto3" json:"payment_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentUserResponse) Reset() {
	*x = GetPaymentUserResponse{}
	mi := &file_donation_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentUserResponse) ProtoMessage() {}

func (x *GetPaymentUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentUserResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentUserResponse) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetPaymentUserResponse) GetPaymentUser() *PaymentUser {
	if x != nil {
		return x.PaymentUser
	}
	return nil
}

type UpdatePaymentUserRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	DisplayName   *sharedpb.OptionalString `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Link          *sharedpb.OptionalString `protobuf:"bytes,2,opt,name=link,proto3,oneof" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentUserRequest) Reset() {
	*x = UpdatePaymentUserRequest{}
	mi := &file_donation_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentUserRequest) ProtoMessage() {}

func (x *UpdatePaymentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentUserRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentUserRequest) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePaymentUserRequest) GetDisplayName() *sharedpb.OptionalString {
	if x != nil {
		return x.DisplayName
	}
	return nil
}

func (x *UpdatePaymentUserRequest) GetLink() *sharedpb.OptionalString {
	if x != nil {
		return x.Link
	}
	return nil
}

type UpdatePaymentUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentUser   *PaymentUser           `protobuf:"bytes,1,opt,name=payment_user,json=paymentUser,proto3" json:"payment_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentUserResponse) Reset() {
	*x = UpdatePaymentUserResponse{}
	mi := &file_donation_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentUserResponse) ProtoMessage() {}

func (x *UpdatePaymentUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentUserResponse.ProtoReflect.Descriptor instead.
func (*UpdatePaymentUserResponse) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePaymentUserResponse) GetPaymentUser() *PaymentUser {
	if x != nil {
		return x.PaymentUser
	}
	return nil
}

type ListPaymentHistoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentHistoriesRequest) Reset() {
	*x = ListPaymentHistoriesRequest{}
	mi := &file_donation_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentHistoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentHistoriesRequest) ProtoMessage() {}

func (x *ListPaymentHistoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentHistoriesRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentHistoriesRequest) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{8}
}

type ListPaymentHistoriesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PaymentHistories []*PaymentHistory      `protobuf:"bytes,1,rep,name=payment_histories,json=paymentHistories,proto3" json:"payment_histories,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListPaymentHistoriesResponse) Reset() {
	*x = ListPaymentHistoriesResponse{}
	mi := &file_donation_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentHistoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentHistoriesResponse) ProtoMessage() {}

func (x *ListPaymentHistoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentHistoriesResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentHistoriesResponse) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListPaymentHistoriesResponse) GetPaymentHistories() []*PaymentHistory {
	if x != nil {
		return x.PaymentHistories
	}
	return nil
}

type ListSubscriptionPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionPlansRequest) Reset() {
	*x = ListSubscriptionPlansRequest{}
	mi := &file_donation_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionPlansRequest) ProtoMessage() {}

func (x *ListSubscriptionPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionPlansRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionPlansRequest) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{10}
}

type ListSubscriptionPlansResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionPlans []*SubscriptionPlan    `protobuf:"bytes,1,rep,name=subscription_plans,json=subscriptionPlans,proto3" json:"subscription_plans,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListSubscriptionPlansResponse) Reset() {
	*x = ListSubscriptionPlansResponse{}
	mi := &file_donation_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionPlansResponse) ProtoMessage() {}

func (x *ListSubscriptionPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionPlansResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionPlansResponse) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListSubscriptionPlansResponse) GetSubscriptionPlans() []*SubscriptionPlan {
	if x != nil {
		return x.SubscriptionPlans
	}
	return nil
}

type GetActiveSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveSubscriptionRequest) Reset() {
	*x = GetActiveSubscriptionRequest{}
	mi := &file_donation_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveSubscriptionRequest) ProtoMessage() {}

func (x *GetActiveSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetActiveSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{12}
}

type GetActiveSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveSubscriptionResponse) Reset() {
	*x = GetActiveSubscriptionResponse{}
	mi := &file_donation_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveSubscriptionResponse) ProtoMessage() {}

func (x *GetActiveSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetActiveSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetActiveSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_donation_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *UnsubscribeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	mi := &file_donation_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{15}
}

type GetTotalAmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalAmountRequest) Reset() {
	*x = GetTotalAmountRequest{}
	mi := &file_donation_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalAmountRequest) ProtoMessage() {}

func (x *GetTotalAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalAmountRequest.ProtoReflect.Descriptor instead.
func (*GetTotalAmountRequest) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{16}
}

type GetTotalAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalAmount   int32                  `protobuf:"varint,1,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalAmountResponse) Reset() {
	*x = GetTotalAmountResponse{}
	mi := &file_donation_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalAmountResponse) ProtoMessage() {}

func (x *GetTotalAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalAmountResponse.ProtoReflect.Descriptor instead.
func (*GetTotalAmountResponse) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetTotalAmountResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type ListContributorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContributorsRequest) Reset() {
	*x = ListContributorsRequest{}
	mi := &file_donation_v1_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContributorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContributorsRequest) ProtoMessage() {}

func (x *ListContributorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContributorsRequest.ProtoReflect.Descriptor instead.
func (*ListContributorsRequest) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{18}
}

type ListContributorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contributors  []*Contributor         `protobuf:"bytes,1,rep,name=contributors,proto3" json:"contributors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContributorsResponse) Reset() {
	*x = ListContributorsResponse{}
	mi := &file_donation_v1_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContributorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContributorsResponse) ProtoMessage() {}

func (x *ListContributorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_donation_v1_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContributorsResponse.ProtoReflect.Descriptor instead.
func (*ListContributorsResponse) Descriptor() ([]byte, []int) {
	return file_donation_v1_service_proto_rawDescGZIP(), []int{19}
}

func (x *ListContributorsResponse) GetContributors() []*Contributor {
	if x != nil {
		return x.Contributors
	}
	return nil
}

var File_donation_v1_service_proto protoreflect.FileDescriptor

const file_donation_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19donation/v1/service.proto\x12\vdonation.v1\x1a\x16donation/v1/type.proto\x1a\x13shared/option.proto\x1a\x11shared/type.proto\"=\n" +
	"#CreateOneTimeCheckoutSessionRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\"V\n" +
	"$CreateOneTimeCheckoutSessionResponse\x12.\n" +
	"\x13checkout_session_id\x18\x01 \x01(\tR\x11checkoutSessionId\"C\n" +
	"(CreateSubscriptionCheckoutSessionRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\"[\n" +
	")CreateSubscriptionCheckoutSessionResponse\x12.\n" +
	"\x13checkout_session_id\x18\x01 \x01(\tR\x11checkoutSessionId\"\x17\n" +
	"\x15GetPaymentUserRequest\"U\n" +
	"\x16GetPaymentUserResponse\x12;\n" +
	"\fpayment_user\x18\x01 \x01(\v2\x18.donation.v1.PaymentUserR\vpaymentUser\"\xa5\x01\n" +
	"\x18UpdatePaymentUserRequest\x12>\n" +
	"\fdisplay_name\x18\x01 \x01(\v2\x16.shared.OptionalStringH\x00R\vdisplayName\x88\x01\x01\x12/\n" +
	"\x04link\x18\x02 \x01(\v2\x16.shared.OptionalStringH\x01R\x04link\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\a\n" +
	"\x05_link\"X\n" +
	"\x19UpdatePaymentUserResponse\x12;\n" +
	"\fpayment_user\x18\x01 \x01(\v2\x18.donation.v1.PaymentUserR\vpaymentUser\"\x1d\n" +
	"\x1bListPaymentHistoriesRequest\"h\n" +
	"\x1cListPaymentHistoriesResponse\x12H\n" +
	"\x11payment_histories\x18\x01 \x03(\v2\x1b.donation.v1.PaymentHistoryR\x10paymentHistories\"\x1e\n" +
	"\x1cListSubscriptionPlansRequest\"m\n" +
	"\x1dListSubscriptionPlansResponse\x12L\n" +
	"\x12subscription_plans\x18\x01 \x03(\v2\x1d.donation.v1.SubscriptionPlanR\x11subscriptionPlans\"\x1e\n" +
	"\x1cGetActiveSubscriptionRequest\"^\n" +
	"\x1dGetActiveSubscriptionResponse\x12=\n" +
	"\fsubscription\x18\x01 \x01(\v2\x19.donation.v1.SubscriptionR\fsubscription\"$\n" +
	"\x12UnsubscribeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13UnsubscribeResponse\"\x17\n" +
	"\x15GetTotalAmountRequest\";\n" +
	"\x16GetTotalAmountResponse\x12!\n" +
	"\ftotal_amount\x18\x01 \x01(\x05R\vtotalAmount\"\x19\n" +
	"\x17ListContributorsRequest\"X\n" +
	"\x18ListContributorsResponse\x12<\n" +
	"\fcontributors\x18\x01 \x03(\v2\x18.donation.v1.ContributorR\fcontributors2\xb4\n" +
	"\n" +
	"\x0fDonationService\x12\x8b\x01\n" +
	"\x1cCreateOneTimeCheckoutSession\x120.donation.v1.CreateOneTimeCheckoutSessionRequest\x1a1.donation.v1.CreateOneTimeCheckoutSessionResponse\"\x06\x82\xb5\x18\x02\b\x02\x12\xe7\x01\n" +
	"!CreateSubscriptionCheckoutSession\x125.donation.v1.CreateSubscriptionCheckoutSessionRequest\x1a6.donation.v1.CreateSubscriptionCheckoutSessionResponse\"S\x82\xb5\x18O\b\x03\x12(donation.ActiveSubscriptionAlreadyExists\x12!donation.SubscriptionPlanNotFound\x12d\n" +
	"\x0eGetPaymentUser\x12\".donation.v1.GetPaymentUserRequest\x1a#.donation.v1.GetPaymentUserResponse\"\t\x82\xb5\x18\x02\b\x03\x90\x02\x01\x12j\n" +
	"\x11UpdatePaymentUser\x12%.donation.v1.UpdatePaymentUserRequest\x1a&.donation.v1.UpdatePaymentUserResponse\"\x06\x82\xb5\x18\x02\b\x03\x12v\n" +
	"\x14ListPaymentHistories\x12(.donation.v1.ListPaymentHistoriesRequest\x1a).donation.v1.ListPaymentHistoriesResponse\"\t\x82\xb5\x18\x02\b\x03\x90\x02\x01\x12y\n" +
	"\x15ListSubscriptionPlans\x12).donation.v1.ListSubscriptionPlansRequest\x1a*.donation.v1.ListSubscriptionPlansResponse\"\t\x82\xb5\x18\x02\b\x01\x90\x02\x01\x12\x98\x01\n" +
	"\x15GetActiveSubscription\x12).donation.v1.GetActiveSubscriptionRequest\x1a*.donation.v1.GetActiveSubscriptionResponse\"(\x82\xb5\x18!\b\x03\x12\x1ddonation.SubscriptionNotFound\x90\x02\x01\x12w\n" +
	"\vUnsubscribe\x12\x1f.donation.v1.UnsubscribeRequest\x1a .donation.v1.UnsubscribeResponse\"%\x82\xb5\x18!\b\x03\x12\x1ddonation.SubscriptionNotFound\x12d\n" +
	"\x0eGetTotalAmount\x12\".donation.v1.GetTotalAmountRequest\x1a#.donation.v1.GetTotalAmountResponse\"\t\x82\xb5\x18\x02\b\x01\x90\x02\x01\x12j\n" +
	"\x10ListContributors\x12$.donation.v1.ListContributorsRequest\x1a%.donation.v1.ListContributorsResponse\"\t\x82\xb5\x18\x02\b\x01\x90\x02\x01Bj\n" +
	"\x1anet.twinte.api.donation.v1ZLgithub.com/twin-te/twin-te/back/handler/api/v4/rpcgen/donation/v1;donationv1b\x06proto3"

var (
	file_donation_v1_service_proto_rawDescOnce sync.Once
	file_donation_v1_service_proto_rawDescData []byte
)

func file_donation_v1_service_proto_rawDescGZIP() []byte {
	file_donation_v1_service_proto_rawDescOnce.Do(func() {
		file_donation_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_donation_v1_service_proto_rawDesc), len(file_donation_v1_service_proto_rawDesc)))
	})
	return file_donation_v1_service_proto_rawDescData
}

var file_donation_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_donation_v1_service_proto_goTypes = []any{
	(*CreateOneTimeCheckoutSessionRequest)(nil),       // 0: donation.v1.CreateOneTimeCheckoutSessionRequest
	(*CreateOneTimeCheckoutSessionResponse)(nil),      // 1: donation.v1.CreateOneTimeCheckoutSessionResponse
	(*CreateSubscriptionCheckoutSessionRequest)(nil),  // 2: donation.v1.CreateSubscriptionCheckoutSessionRequest
	(*CreateSubscriptionCheckoutSessionResponse)(nil), // 3: donation.v1.CreateSubscriptionCheckoutSessionResponse
	(*GetPaymentUserRequest)(nil),                     // 4: donation.v1.GetPaymentUserRequest
	(*GetPaymentUserResponse)(nil),                    // 5: donation.v1.GetPaymentUserResponse
	(*UpdatePaymentUserRequest)(nil),                  // 6: donation.v1.UpdatePaymentUserRequest
	(*UpdatePaymentUserResponse)(nil),                 // 7: donation.v1.UpdatePaymentUserResponse
	(*ListPaymentHistoriesRequest)(nil),               // 8: donation.v1.ListPaymentHistoriesRequest
	(*ListPaymentHistoriesResponse)(nil),              // 9: donation.v1.ListPaymentHistoriesResponse
	(*ListSubscriptionPlansRequest)(nil),              // 10: donation.v1.ListSubscriptionPlansRequest
	(*ListSubscriptionPlansResponse)(nil),             // 11: donation.v1.ListSubscriptionPlansResponse
	(*GetActiveSubscriptionRequest)(nil),              // 12: donation.v1.GetActiveSubscriptionRequest
	(*GetActiveSubscriptionResponse)(nil),             // 13: donation.v1.GetActiveSubscriptionResponse
	(*UnsubscribeRequest)(nil),                        // 14: donation.v1.UnsubscribeRequest
	(*UnsubscribeResponse)(nil),                       // 15: donation.v1.UnsubscribeResponse
	(*GetTotalAmountRequest)(nil),                     // 16: donation.v1.GetTotalAmountRequest
	(*GetTotalAmountResponse)(nil),                    // 17: donation.v1.GetTotalAmountResponse
	(*ListContributorsRequest)(nil),                   // 18: donation.v1.ListContributorsRequest
	(*ListContributorsResponse)(nil),                  // 19: donation.v1.ListContributorsResponse
	(*PaymentUser)(nil),                               // 20: donation.v1.PaymentUser
	(*sharedpb.OptionalString)(nil),                   // 21: shared.OptionalString
	(*PaymentHistory)(nil),                            // 22: donation.v1.PaymentHistory
	(*SubscriptionPlan)(nil),                          // 23: donation.v1.SubscriptionPlan
	(*Subscription)(nil),                              // 24: donation.v1.Subscription
	(*Contributor)(nil),                               // 25: donation.v1.Contributor
}
var file_donation_v1_service_proto_depIdxs = []int32{
	20, // 0: donation.v1.GetPaymentUserResponse.payment_user:type_name -> donation.v1.PaymentUser
	21, // 1: donation.v1.UpdatePaymentUserRequest.display_name:type_name -> shared.OptionalString
	21, // 2: donation.v1.UpdatePaymentUserRequest.link:type_name -> shared.OptionalString
	20, // 3: donation.v1.UpdatePaymentUserResponse.payment_user:type_name -> donation.v1.PaymentUser
	22, // 4: donation.v1.ListPaymentHistoriesResponse.payment_histories:type_name -> donation.v1.PaymentHistory
	23, // 5: donation.v1.ListSubscriptionPlansResponse.subscription_plans:type_name -> donation.v1.SubscriptionPlan
	24, // 6: donation.v1.GetActiveSubscriptionResponse.subscription:type_name -> donation.v1.Subscription
	25, // 7: donation.v1.ListContributorsResponse.contributors:type_name -> donation.v1.Contributor
	0,  // 8: donation.v1.DonationService.CreateOneTimeCheckoutSession:input_type -> donation.v1.CreateOneTimeCheckoutSessionRequest
	2,  // 9: donation.v1.DonationService.CreateSubscriptionCheckoutSession:input_type -> donation.v1.CreateSubscriptionCheckoutSessionRequest
	4,  // 10: donation.v1.DonationService.GetPaymentUser:input_type -> donation.v1.GetPaymentUserRequest
	6,  // 11: donation.v1.DonationService.UpdatePaymentUser:input_type -> donation.v1.UpdatePaymentUserRequest
	8,  // 12: donation.v1.DonationService.ListPaymentHistories:input_type -> donation.v1.ListPaymentHistoriesRequest
	10, // 13: donation.v1.DonationService.ListSubscriptionPlans:input_type -> donation.v1.ListSubscriptionPlansRequest
	12, // 14: donation.v1.DonationService.GetActiveSubscription:input_type -> donation.v1.GetActiveSubscriptionRequest
	14, // 15: donation.v1.DonationService.Unsubscribe:input_type -> donation.v1.UnsubscribeRequest
	16, // 16: donation.v1.DonationService.GetTotalAmount:input_type -> donation.v1.GetTotalAmountRequest
	18, // 17: donation.v1.DonationService.ListContributors:input_type -> donation.v1.ListContributorsRequest
	1,  // 18: donation.v1.DonationService.CreateOneTimeCheckoutSession:output_type -> donation.v1.CreateOneTimeCheckoutSessionResponse
	3,  // 19: donation.v1.DonationService.CreateSubscriptionCheckoutSession:output_type -> donation.v1.CreateSubscriptionCheckoutSessionResponse
	5,  // 20: donation.v1.DonationService.GetPaymentUser:output_type -> donation.v1.GetPaymentUserResponse
	7,  // 21: donation.v1.DonationService.UpdatePaymentUser:output_type -> donation.v1.UpdatePaymentUserResponse
	9,  // 22: donation.v1.DonationService.ListPaymentHistories:output_type -> donation.v1.ListPaymentHistoriesResponse
	11, // 23: donation.v1.DonationService.ListSubscriptionPlans:output_type -> donation.v1.ListSubscriptionPlansResponse
	13, // 24: donation.v1.DonationService.GetActiveSubscription:output_type -> donation.v1.GetActiveSubscriptionResponse
	15, // 25: donation.v1.DonationService.Unsubscribe:output_type -> donation.v1.UnsubscribeResponse
	17, // 26: donation.v1.DonationService.GetTotalAmount:output_type -> donation.v1.GetTotalAmountResponse
	19, // 27: donation.v1.DonationService.ListContributors:output_type -> donation.v1.ListContributorsResponse
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_donation_v1_service_proto_init() }
func file_donation_v1_service_proto_init() {
	if File_donation_v1_service_proto != nil {
		return
	}
	file_donation_v1_type_proto_init()
	file_donation_v1_service_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_donation_v1_service_proto_rawDesc), len(file_donation_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_donation_v1_service_proto_goTypes,
		DependencyIndexes: file_donation_v1_service_proto_depIdxs,
		MessageInfos:      file_donation_v1_service_proto_msgTypes,
	}.Build()
	File_donation_v1_service_proto = out.File
	file_donation_v1_service_proto_goTypes = nil
	file_donation_v1_service_proto_depIdxs = nil
}
