// Code generated by codegen/idtype/generate.py; DO NOT EDIT.

package idtype

import (
	"database/sql/driver"	
	"fmt"

	"github.com/google/uuid"
)

type AlreadyReadID uuid.UUID

func (id AlreadyReadID) String() string {
	return uuid.UUID(id).String()
}

func (id AlreadyReadID) IsZero() bool {
	return uuid.UUID(id) == uuid.Nil
}

func (id AlreadyReadID) Less(other AlreadyReadID) bool {
	for i := 0; i < 16; i++ {
		if id[i] == other[i] {
			continue
		}
		return id[i] < other[i]
	}
	return false
}

func (id *AlreadyReadID) Scan(src interface{}) error {
	uuid := new(uuid.UUID)
	if err := uuid.Scan(src); err != nil {
		return err
	}
	*id = AlreadyReadID(*uuid)
	return nil
}

func (id AlreadyReadID) Value() (driver.Value, error) {
	return id.String(), nil
}

func NewAlreadyReadID() AlreadyReadID {
	return AlreadyReadID(uuid.New())
}

func ParseAlreadyReadID(s string) (AlreadyReadID, error) {
	id, err := uuid.Parse(s)
	if err != nil {
		return AlreadyReadID{}, fmt.Errorf("failed to parse AlreadyReadID %v", s)
	}
	return AlreadyReadID(id), nil
}
