// Code generated by codegen/idtype/generate.py; DO NOT EDIT.

package idtype

import "fmt"

type CheckoutSessionID string

func (id CheckoutSessionID) String() string {
	return string(id)
}

func (id CheckoutSessionID) IsZero() bool {
	return id == ""
}

func (id *CheckoutSessionID) Scan(src interface{}) error {
	switch src := src.(type) {
	case nil:
		return nil
	case string:
		*id = CheckoutSessionID(src)
		return nil
	default:
		return fmt.Errorf("Scan: unable to scan type %T into CheckoutSessionID", src)
	}
}

func ParseCheckoutSessionID(s string) (CheckoutSessionID, error) {
	if s == "" {
		return "", fmt.Errorf("failed to parse CheckoutSessionID %#v", s)
	}
	return CheckoutSessionID(s), nil
}
