// Code generated by codegen/idtype/generate.py; DO NOT EDIT.

package idtype

import (
	"database/sql/driver"	
	"fmt"

	"github.com/google/uuid"
)

type CourseID uuid.UUID

func (id CourseID) String() string {
	return uuid.UUID(id).String()
}

func (id CourseID) IsZero() bool {
	return uuid.UUID(id) == uuid.Nil
}

func (id CourseID) Less(other CourseID) bool {
	for i := 0; i < 16; i++ {
		if id[i] == other[i] {
			continue
		}
		return id[i] < other[i]
	}
	return false
}

func (id *CourseID) Scan(src interface{}) error {
	uuid := new(uuid.UUID)
	if err := uuid.Scan(src); err != nil {
		return err
	}
	*id = CourseID(*uuid)
	return nil
}

func (id CourseID) Value() (driver.Value, error) {
	return id.String(), nil
}

func NewCourseID() CourseID {
	return CourseID(uuid.New())
}

func ParseCourseID(s string) (CourseID, error) {
	id, err := uuid.Parse(s)
	if err != nil {
		return CourseID{}, fmt.Errorf("failed to parse CourseID %v", s)
	}
	return CourseID(id), nil
}
