// Code generated by codegen/idtype/generate.py; DO NOT EDIT.

package idtype

import (
	"fmt"

	"github.com/google/uuid"
	"github.com/samber/lo"
)

type IcalSubscriptionID uuid.UUID

func (id IcalSubscriptionID) String() string {
	return uuid.UUID(id).String()
}

func (id IcalSubscriptionID) IsZero() bool {
	return uuid.UUID(id) == uuid.Nil
}

func (id IcalSubscriptionID) Less(other IcalSubscriptionID) bool {
	for i := 0; i < 16; i++ {
		if id[i] == other[i] {
			continue
		}
		return id[i] < other[i]
	}
	return false
}

func (id *IcalSubscriptionID) StringPtr() *string {
	if id == nil {
		return nil
	}
	return lo.ToPtr(id.String())
}

func NewIcalSubscriptionID() IcalSubscriptionID {
	return IcalSubscriptionID(uuid.New())
}

func ParseIcalSubscriptionID(s string) (IcalSubscriptionID, error) {
	id, err := uuid.Parse(s)
	if err != nil {
		return IcalSubscriptionID{}, fmt.Errorf("failed to parse IcalSubscriptionID %v", s)
	}
	return IcalSubscriptionID(id), nil
}
