// Code generated by codegen/idtype/generate.py; DO NOT EDIT.

package idtype

import (
	"database/sql/driver"	
	"fmt"

	"github.com/google/uuid"
)

type RegisteredCourseID uuid.UUID

func (id RegisteredCourseID) String() string {
	return uuid.UUID(id).String()
}

func (id RegisteredCourseID) IsZero() bool {
	return uuid.UUID(id) == uuid.Nil
}

func (id RegisteredCourseID) Less(other RegisteredCourseID) bool {
	for i := 0; i < 16; i++ {
		if id[i] == other[i] {
			continue
		}
		return id[i] < other[i]
	}
	return false
}

func (id *RegisteredCourseID) Scan(src interface{}) error {
	uuid := new(uuid.UUID)
	if err := uuid.Scan(src); err != nil {
		return err
	}
	*id = RegisteredCourseID(*uuid)
	return nil
}

func (id RegisteredCourseID) Value() (driver.Value, error) {
	return id.String(), nil
}

func NewRegisteredCourseID() RegisteredCourseID {
	return RegisteredCourseID(uuid.New())
}

func ParseRegisteredCourseID(s string) (RegisteredCourseID, error) {
	id, err := uuid.Parse(s)
	if err != nil {
		return RegisteredCourseID{}, fmt.Errorf("failed to parse RegisteredCourseID %v", s)
	}
	return RegisteredCourseID(id), nil
}
