// Code generated by codegen/idtype/generate.py; DO NOT EDIT.

package idtype

import (
	"database/sql/driver"	
	"fmt"

	"github.com/google/uuid"
)

type SessionID uuid.UUID

func (id SessionID) String() string {
	return uuid.UUID(id).String()
}

func (id SessionID) IsZero() bool {
	return uuid.UUID(id) == uuid.Nil
}

func (id SessionID) Less(other SessionID) bool {
	for i := 0; i < 16; i++ {
		if id[i] == other[i] {
			continue
		}
		return id[i] < other[i]
	}
	return false
}

func (id *SessionID) Scan(src interface{}) error {
	uuid := new(uuid.UUID)
	if err := uuid.Scan(src); err != nil {
		return err
	}
	*id = SessionID(*uuid)
	return nil
}

func (id SessionID) Value() (driver.Value, error) {
	return id.String(), nil
}

func NewSessionID() SessionID {
	return SessionID(uuid.New())
}

func ParseSessionID(s string) (SessionID, error) {
	id, err := uuid.Parse(s)
	if err != nil {
		return SessionID{}, fmt.Errorf("failed to parse SessionID %v", s)
	}
	return SessionID(id), nil
}
