// Code generated by codegen/error/generate.py; DO NOT EDIT.

package donationerr

import "github.com/twin-te/twin-te/back/apperr"

const (
	CodeSubscriptionNotFound apperr.Code = "donation.SubscriptionNotFound"
)
