// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: announcement/v1/service.proto

package announcementv1

import (
	sharedpb "github.com/twin-te/twin-te/back/handler/api/v4/rpcgen/sharedpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAnnouncementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnnouncementsRequest) Reset() {
	*x = ListAnnouncementsRequest{}
	mi := &file_announcement_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnnouncementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnnouncementsRequest) ProtoMessage() {}

func (x *ListAnnouncementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_announcement_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnnouncementsRequest.ProtoReflect.Descriptor instead.
func (*ListAnnouncementsRequest) Descriptor() ([]byte, []int) {
	return file_announcement_v1_service_proto_rawDescGZIP(), []int{0}
}

type ListAnnouncementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Announcements []*Announcement        `protobuf:"bytes,1,rep,name=announcements,proto3" json:"announcements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnnouncementsResponse) Reset() {
	*x = ListAnnouncementsResponse{}
	mi := &file_announcement_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnnouncementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnnouncementsResponse) ProtoMessage() {}

func (x *ListAnnouncementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_announcement_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnnouncementsResponse.ProtoReflect.Descriptor instead.
func (*ListAnnouncementsResponse) Descriptor() ([]byte, []int) {
	return file_announcement_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListAnnouncementsResponse) GetAnnouncements() []*Announcement {
	if x != nil {
		return x.Announcements
	}
	return nil
}

type ReadAnnouncementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []*sharedpb.UUID       `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAnnouncementsRequest) Reset() {
	*x = ReadAnnouncementsRequest{}
	mi := &file_announcement_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAnnouncementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAnnouncementsRequest) ProtoMessage() {}

func (x *ReadAnnouncementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_announcement_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAnnouncementsRequest.ProtoReflect.Descriptor instead.
func (*ReadAnnouncementsRequest) Descriptor() ([]byte, []int) {
	return file_announcement_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReadAnnouncementsRequest) GetIds() []*sharedpb.UUID {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ReadAnnouncementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAnnouncementsResponse) Reset() {
	*x = ReadAnnouncementsResponse{}
	mi := &file_announcement_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAnnouncementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAnnouncementsResponse) ProtoMessage() {}

func (x *ReadAnnouncementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_announcement_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAnnouncementsResponse.ProtoReflect.Descriptor instead.
func (*ReadAnnouncementsResponse) Descriptor() ([]byte, []int) {
	return file_announcement_v1_service_proto_rawDescGZIP(), []int{3}
}

var File_announcement_v1_service_proto protoreflect.FileDescriptor

const file_announcement_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1dannouncement/v1/service.proto\x12\x0fannouncement.v1\x1a\x1aannouncement/v1/type.proto\x1a\x13shared/option.proto\x1a\x11shared/type.proto\"\x1a\n" +
	"\x18ListAnnouncementsRequest\"`\n" +
	"\x19ListAnnouncementsResponse\x12C\n" +
	"\rannouncements\x18\x01 \x03(\v2\x1d.announcement.v1.AnnouncementR\rannouncements\":\n" +
	"\x18ReadAnnouncementsRequest\x12\x1e\n" +
	"\x03ids\x18\x01 \x03(\v2\f.shared.UUIDR\x03ids\"\x1b\n" +
	"\x19ReadAnnouncementsResponse2\xa4\x02\n" +
	"\x13AnnouncementService\x12u\n" +
	"\x11ListAnnouncements\x12).announcement.v1.ListAnnouncementsRequest\x1a*.announcement.v1.ListAnnouncementsResponse\"\t\x82\xb5\x18\x02\b\x02\x90\x02\x01\x12\x95\x01\n" +
	"\x11ReadAnnouncements\x12).announcement.v1.ReadAnnouncementsRequest\x1a*.announcement.v1.ReadAnnouncementsResponse\")\x82\xb5\x18%\b\x03\x12!announcement.AnnouncementNotFoundBv\n" +
	"\x1enet.twinte.api.announcement.v1ZTgithub.com/twin-te/twin-te/back/handler/api/v4/rpcgen/announcement/v1;announcementv1b\x06proto3"

var (
	file_announcement_v1_service_proto_rawDescOnce sync.Once
	file_announcement_v1_service_proto_rawDescData []byte
)

func file_announcement_v1_service_proto_rawDescGZIP() []byte {
	file_announcement_v1_service_proto_rawDescOnce.Do(func() {
		file_announcement_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_announcement_v1_service_proto_rawDesc), len(file_announcement_v1_service_proto_rawDesc)))
	})
	return file_announcement_v1_service_proto_rawDescData
}

var file_announcement_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_announcement_v1_service_proto_goTypes = []any{
	(*ListAnnouncementsRequest)(nil),  // 0: announcement.v1.ListAnnouncementsRequest
	(*ListAnnouncementsResponse)(nil), // 1: announcement.v1.ListAnnouncementsResponse
	(*ReadAnnouncementsRequest)(nil),  // 2: announcement.v1.ReadAnnouncementsRequest
	(*ReadAnnouncementsResponse)(nil), // 3: announcement.v1.ReadAnnouncementsResponse
	(*Announcement)(nil),              // 4: announcement.v1.Announcement
	(*sharedpb.UUID)(nil),             // 5: shared.UUID
}
var file_announcement_v1_service_proto_depIdxs = []int32{
	4, // 0: announcement.v1.ListAnnouncementsResponse.announcements:type_name -> announcement.v1.Announcement
	5, // 1: announcement.v1.ReadAnnouncementsRequest.ids:type_name -> shared.UUID
	0, // 2: announcement.v1.AnnouncementService.ListAnnouncements:input_type -> announcement.v1.ListAnnouncementsRequest
	2, // 3: announcement.v1.AnnouncementService.ReadAnnouncements:input_type -> announcement.v1.ReadAnnouncementsRequest
	1, // 4: announcement.v1.AnnouncementService.ListAnnouncements:output_type -> announcement.v1.ListAnnouncementsResponse
	3, // 5: announcement.v1.AnnouncementService.ReadAnnouncements:output_type -> announcement.v1.ReadAnnouncementsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_announcement_v1_service_proto_init() }
func file_announcement_v1_service_proto_init() {
	if File_announcement_v1_service_proto != nil {
		return
	}
	file_announcement_v1_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_announcement_v1_service_proto_rawDesc), len(file_announcement_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_announcement_v1_service_proto_goTypes,
		DependencyIndexes: file_announcement_v1_service_proto_depIdxs,
		MessageInfos:      file_announcement_v1_service_proto_msgTypes,
	}.Build()
	File_announcement_v1_service_proto = out.File
	file_announcement_v1_service_proto_goTypes = nil
	file_announcement_v1_service_proto_depIdxs = nil
}
