// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: announcement/v1/type.proto

package announcementv1

import (
	sharedpb "github.com/twin-te/twin-te/back/handler/api/v4/rpcgen/sharedpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnnouncementTag int32

const (
	AnnouncementTag_ANNOUNCEMENT_TAG_UNSPECIFIED  AnnouncementTag = 0
	AnnouncementTag_ANNOUNCEMENT_TAG_INFORMATION  AnnouncementTag = 1
	AnnouncementTag_ANNOUNCEMENT_TAG_NOTIFICATION AnnouncementTag = 2
)

// Enum value maps for AnnouncementTag.
var (
	AnnouncementTag_name = map[int32]string{
		0: "ANNOUNCEMENT_TAG_UNSPECIFIED",
		1: "ANNOUNCEMENT_TAG_INFORMATION",
		2: "ANNOUNCEMENT_TAG_NOTIFICATION",
	}
	AnnouncementTag_value = map[string]int32{
		"ANNOUNCEMENT_TAG_UNSPECIFIED":  0,
		"ANNOUNCEMENT_TAG_INFORMATION":  1,
		"ANNOUNCEMENT_TAG_NOTIFICATION": 2,
	}
)

func (x AnnouncementTag) Enum() *AnnouncementTag {
	p := new(AnnouncementTag)
	*p = x
	return p
}

func (x AnnouncementTag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnouncementTag) Descriptor() protoreflect.EnumDescriptor {
	return file_announcement_v1_type_proto_enumTypes[0].Descriptor()
}

func (AnnouncementTag) Type() protoreflect.EnumType {
	return &file_announcement_v1_type_proto_enumTypes[0]
}

func (x AnnouncementTag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnnouncementTag.Descriptor instead.
func (AnnouncementTag) EnumDescriptor() ([]byte, []int) {
	return file_announcement_v1_type_proto_rawDescGZIP(), []int{0}
}

// If authenticated, is_read is present.
type Announcement struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            *sharedpb.UUID            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tags          []AnnouncementTag         `protobuf:"varint,2,rep,packed,name=tags,proto3,enum=announcement.v1.AnnouncementTag" json:"tags,omitempty"`
	Title         string                    `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                    `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	PublishedAt   *sharedpb.RFC3339DateTime `protobuf:"bytes,5,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	IsRead        *bool                     `protobuf:"varint,6,opt,name=is_read,json=isRead,proto3,oneof" json:"is_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Announcement) Reset() {
	*x = Announcement{}
	mi := &file_announcement_v1_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Announcement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Announcement) ProtoMessage() {}

func (x *Announcement) ProtoReflect() protoreflect.Message {
	mi := &file_announcement_v1_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Announcement.ProtoReflect.Descriptor instead.
func (*Announcement) Descriptor() ([]byte, []int) {
	return file_announcement_v1_type_proto_rawDescGZIP(), []int{0}
}

func (x *Announcement) GetId() *sharedpb.UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Announcement) GetTags() []AnnouncementTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Announcement) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Announcement) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Announcement) GetPublishedAt() *sharedpb.RFC3339DateTime {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Announcement) GetIsRead() bool {
	if x != nil && x.IsRead != nil {
		return *x.IsRead
	}
	return false
}

var File_announcement_v1_type_proto protoreflect.FileDescriptor

const file_announcement_v1_type_proto_rawDesc = "" +
	"\n" +
	"\x1aannouncement/v1/type.proto\x12\x0fannouncement.v1\x1a\x11shared/type.proto\"\xf8\x01\n" +
	"\fAnnouncement\x12\x1c\n" +
	"\x02id\x18\x01 \x01(\v2\f.shared.UUIDR\x02id\x124\n" +
	"\x04tags\x18\x02 \x03(\x0e2 .announcement.v1.AnnouncementTagR\x04tags\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12:\n" +
	"\fpublished_at\x18\x05 \x01(\v2\x17.shared.RFC3339DateTimeR\vpublishedAt\x12\x1c\n" +
	"\ais_read\x18\x06 \x01(\bH\x00R\x06isRead\x88\x01\x01B\n" +
	"\n" +
	"\b_is_read*x\n" +
	"\x0fAnnouncementTag\x12 \n" +
	"\x1cANNOUNCEMENT_TAG_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cANNOUNCEMENT_TAG_INFORMATION\x10\x01\x12!\n" +
	"\x1dANNOUNCEMENT_TAG_NOTIFICATION\x10\x02Bv\n" +
	"\x1enet.twinte.api.announcement.v1ZTgithub.com/twin-te/twin-te/back/handler/api/v4/rpcgen/announcement/v1;announcementv1b\x06proto3"

var (
	file_announcement_v1_type_proto_rawDescOnce sync.Once
	file_announcement_v1_type_proto_rawDescData []byte
)

func file_announcement_v1_type_proto_rawDescGZIP() []byte {
	file_announcement_v1_type_proto_rawDescOnce.Do(func() {
		file_announcement_v1_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_announcement_v1_type_proto_rawDesc), len(file_announcement_v1_type_proto_rawDesc)))
	})
	return file_announcement_v1_type_proto_rawDescData
}

var file_announcement_v1_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_announcement_v1_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_announcement_v1_type_proto_goTypes = []any{
	(AnnouncementTag)(0),             // 0: announcement.v1.AnnouncementTag
	(*Announcement)(nil),             // 1: announcement.v1.Announcement
	(*sharedpb.UUID)(nil),            // 2: shared.UUID
	(*sharedpb.RFC3339DateTime)(nil), // 3: shared.RFC3339DateTime
}
var file_announcement_v1_type_proto_depIdxs = []int32{
	2, // 0: announcement.v1.Announcement.id:type_name -> shared.UUID
	0, // 1: announcement.v1.Announcement.tags:type_name -> announcement.v1.AnnouncementTag
	3, // 2: announcement.v1.Announcement.published_at:type_name -> shared.RFC3339DateTime
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_announcement_v1_type_proto_init() }
func file_announcement_v1_type_proto_init() {
	if File_announcement_v1_type_proto != nil {
		return
	}
	file_announcement_v1_type_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_announcement_v1_type_proto_rawDesc), len(file_announcement_v1_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_announcement_v1_type_proto_goTypes,
		DependencyIndexes: file_announcement_v1_type_proto_depIdxs,
		EnumInfos:         file_announcement_v1_type_proto_enumTypes,
		MessageInfos:      file_announcement_v1_type_proto_msgTypes,
	}.Build()
	File_announcement_v1_type_proto = out.File
	file_announcement_v1_type_proto_goTypes = nil
	file_announcement_v1_type_proto_depIdxs = nil
}
