// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: calendar/v1/service.proto

package calendarv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/twin-te/twin-te/back/handler/api/v4/rpcgen/calendar/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion1_7_0

const (
	// CalendarServiceName is the fully-qualified name of the CalendarService service.
	CalendarServiceName = "calendar.v1.CalendarService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CalendarServiceGetIcalSubscriptionUrlProcedure is the fully-qualified name of the
	// CalendarService's GetIcalSubscriptionUrl RPC.
	CalendarServiceGetIcalSubscriptionUrlProcedure = "/calendar.v1.CalendarService/GetIcalSubscriptionUrl"
	// CalendarServiceEnableIcalSubscriptionProcedure is the fully-qualified name of the
	// CalendarService's EnableIcalSubscription RPC.
	CalendarServiceEnableIcalSubscriptionProcedure = "/calendar.v1.CalendarService/EnableIcalSubscription"
	// CalendarServiceDisableIcalSubscriptionProcedure is the fully-qualified name of the
	// CalendarService's DisableIcalSubscription RPC.
	CalendarServiceDisableIcalSubscriptionProcedure = "/calendar.v1.CalendarService/DisableIcalSubscription"
)

// CalendarServiceClient is a client for the calendar.v1.CalendarService service.
type CalendarServiceClient interface {
	GetIcalSubscriptionUrl(context.Context, *connect_go.Request[v1.GetIcalSubscriptionUrlRequest]) (*connect_go.Response[v1.GetIcalSubscriptionUrlResponse], error)
	EnableIcalSubscription(context.Context, *connect_go.Request[v1.EnableIcalSubscriptionRequest]) (*connect_go.Response[v1.EnableIcalSubscriptionResponse], error)
	DisableIcalSubscription(context.Context, *connect_go.Request[v1.DisableIcalSubscriptionRequest]) (*connect_go.Response[v1.DisableIcalSubscriptionResponse], error)
}

// NewCalendarServiceClient constructs a client for the calendar.v1.CalendarService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCalendarServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) CalendarServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &calendarServiceClient{
		getIcalSubscriptionUrl: connect_go.NewClient[v1.GetIcalSubscriptionUrlRequest, v1.GetIcalSubscriptionUrlResponse](
			httpClient,
			baseURL+CalendarServiceGetIcalSubscriptionUrlProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		enableIcalSubscription: connect_go.NewClient[v1.EnableIcalSubscriptionRequest, v1.EnableIcalSubscriptionResponse](
			httpClient,
			baseURL+CalendarServiceEnableIcalSubscriptionProcedure,
			opts...,
		),
		disableIcalSubscription: connect_go.NewClient[v1.DisableIcalSubscriptionRequest, v1.DisableIcalSubscriptionResponse](
			httpClient,
			baseURL+CalendarServiceDisableIcalSubscriptionProcedure,
			opts...,
		),
	}
}

// calendarServiceClient implements CalendarServiceClient.
type calendarServiceClient struct {
	getIcalSubscriptionUrl  *connect_go.Client[v1.GetIcalSubscriptionUrlRequest, v1.GetIcalSubscriptionUrlResponse]
	enableIcalSubscription  *connect_go.Client[v1.EnableIcalSubscriptionRequest, v1.EnableIcalSubscriptionResponse]
	disableIcalSubscription *connect_go.Client[v1.DisableIcalSubscriptionRequest, v1.DisableIcalSubscriptionResponse]
}

// GetIcalSubscriptionUrl calls calendar.v1.CalendarService.GetIcalSubscriptionUrl.
func (c *calendarServiceClient) GetIcalSubscriptionUrl(ctx context.Context, req *connect_go.Request[v1.GetIcalSubscriptionUrlRequest]) (*connect_go.Response[v1.GetIcalSubscriptionUrlResponse], error) {
	return c.getIcalSubscriptionUrl.CallUnary(ctx, req)
}

// EnableIcalSubscription calls calendar.v1.CalendarService.EnableIcalSubscription.
func (c *calendarServiceClient) EnableIcalSubscription(ctx context.Context, req *connect_go.Request[v1.EnableIcalSubscriptionRequest]) (*connect_go.Response[v1.EnableIcalSubscriptionResponse], error) {
	return c.enableIcalSubscription.CallUnary(ctx, req)
}

// DisableIcalSubscription calls calendar.v1.CalendarService.DisableIcalSubscription.
func (c *calendarServiceClient) DisableIcalSubscription(ctx context.Context, req *connect_go.Request[v1.DisableIcalSubscriptionRequest]) (*connect_go.Response[v1.DisableIcalSubscriptionResponse], error) {
	return c.disableIcalSubscription.CallUnary(ctx, req)
}

// CalendarServiceHandler is an implementation of the calendar.v1.CalendarService service.
type CalendarServiceHandler interface {
	GetIcalSubscriptionUrl(context.Context, *connect_go.Request[v1.GetIcalSubscriptionUrlRequest]) (*connect_go.Response[v1.GetIcalSubscriptionUrlResponse], error)
	EnableIcalSubscription(context.Context, *connect_go.Request[v1.EnableIcalSubscriptionRequest]) (*connect_go.Response[v1.EnableIcalSubscriptionResponse], error)
	DisableIcalSubscription(context.Context, *connect_go.Request[v1.DisableIcalSubscriptionRequest]) (*connect_go.Response[v1.DisableIcalSubscriptionResponse], error)
}

// NewCalendarServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCalendarServiceHandler(svc CalendarServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	calendarServiceGetIcalSubscriptionUrlHandler := connect_go.NewUnaryHandler(
		CalendarServiceGetIcalSubscriptionUrlProcedure,
		svc.GetIcalSubscriptionUrl,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	calendarServiceEnableIcalSubscriptionHandler := connect_go.NewUnaryHandler(
		CalendarServiceEnableIcalSubscriptionProcedure,
		svc.EnableIcalSubscription,
		opts...,
	)
	calendarServiceDisableIcalSubscriptionHandler := connect_go.NewUnaryHandler(
		CalendarServiceDisableIcalSubscriptionProcedure,
		svc.DisableIcalSubscription,
		opts...,
	)
	return "/calendar.v1.CalendarService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CalendarServiceGetIcalSubscriptionUrlProcedure:
			calendarServiceGetIcalSubscriptionUrlHandler.ServeHTTP(w, r)
		case CalendarServiceEnableIcalSubscriptionProcedure:
			calendarServiceEnableIcalSubscriptionHandler.ServeHTTP(w, r)
		case CalendarServiceDisableIcalSubscriptionProcedure:
			calendarServiceDisableIcalSubscriptionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCalendarServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCalendarServiceHandler struct{}

func (UnimplementedCalendarServiceHandler) GetIcalSubscriptionUrl(context.Context, *connect_go.Request[v1.GetIcalSubscriptionUrlRequest]) (*connect_go.Response[v1.GetIcalSubscriptionUrlResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("calendar.v1.CalendarService.GetIcalSubscriptionUrl is not implemented"))
}

func (UnimplementedCalendarServiceHandler) EnableIcalSubscription(context.Context, *connect_go.Request[v1.EnableIcalSubscriptionRequest]) (*connect_go.Response[v1.EnableIcalSubscriptionResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("calendar.v1.CalendarService.EnableIcalSubscription is not implemented"))
}

func (UnimplementedCalendarServiceHandler) DisableIcalSubscription(context.Context, *connect_go.Request[v1.DisableIcalSubscriptionRequest]) (*connect_go.Response[v1.DisableIcalSubscriptionResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("calendar.v1.CalendarService.DisableIcalSubscription is not implemented"))
}
