// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: calendar/v1/service.proto

package calendarv1

import (
	_ "github.com/twin-te/twin-te/back/handler/api/v4/rpcgen/sharedpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIcalSubscriptionUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIcalSubscriptionUrlRequest) Reset() {
	*x = GetIcalSubscriptionUrlRequest{}
	mi := &file_calendar_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIcalSubscriptionUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIcalSubscriptionUrlRequest) ProtoMessage() {}

func (x *GetIcalSubscriptionUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIcalSubscriptionUrlRequest.ProtoReflect.Descriptor instead.
func (*GetIcalSubscriptionUrlRequest) Descriptor() ([]byte, []int) {
	return file_calendar_v1_service_proto_rawDescGZIP(), []int{0}
}

type GetIcalSubscriptionUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *string                `protobuf:"bytes,1,opt,name=url,proto3,oneof" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIcalSubscriptionUrlResponse) Reset() {
	*x = GetIcalSubscriptionUrlResponse{}
	mi := &file_calendar_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIcalSubscriptionUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIcalSubscriptionUrlResponse) ProtoMessage() {}

func (x *GetIcalSubscriptionUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIcalSubscriptionUrlResponse.ProtoReflect.Descriptor instead.
func (*GetIcalSubscriptionUrlResponse) Descriptor() ([]byte, []int) {
	return file_calendar_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetIcalSubscriptionUrlResponse) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type EnableIcalSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableIcalSubscriptionRequest) Reset() {
	*x = EnableIcalSubscriptionRequest{}
	mi := &file_calendar_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableIcalSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableIcalSubscriptionRequest) ProtoMessage() {}

func (x *EnableIcalSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableIcalSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*EnableIcalSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_calendar_v1_service_proto_rawDescGZIP(), []int{2}
}

type EnableIcalSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableIcalSubscriptionResponse) Reset() {
	*x = EnableIcalSubscriptionResponse{}
	mi := &file_calendar_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableIcalSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableIcalSubscriptionResponse) ProtoMessage() {}

func (x *EnableIcalSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableIcalSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*EnableIcalSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_calendar_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *EnableIcalSubscriptionResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DisableIcalSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableIcalSubscriptionRequest) Reset() {
	*x = DisableIcalSubscriptionRequest{}
	mi := &file_calendar_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableIcalSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableIcalSubscriptionRequest) ProtoMessage() {}

func (x *DisableIcalSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableIcalSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*DisableIcalSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_calendar_v1_service_proto_rawDescGZIP(), []int{4}
}

type DisableIcalSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableIcalSubscriptionResponse) Reset() {
	*x = DisableIcalSubscriptionResponse{}
	mi := &file_calendar_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableIcalSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableIcalSubscriptionResponse) ProtoMessage() {}

func (x *DisableIcalSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableIcalSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*DisableIcalSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_calendar_v1_service_proto_rawDescGZIP(), []int{5}
}

var File_calendar_v1_service_proto protoreflect.FileDescriptor

const file_calendar_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19calendar/v1/service.proto\x12\vcalendar.v1\x1a\x13shared/option.proto\"\x1f\n" +
	"\x1dGetIcalSubscriptionUrlRequest\"?\n" +
	"\x1eGetIcalSubscriptionUrlResponse\x12\x15\n" +
	"\x03url\x18\x01 \x01(\tH\x00R\x03url\x88\x01\x01B\x06\n" +
	"\x04_url\"\x1f\n" +
	"\x1dEnableIcalSubscriptionRequest\"2\n" +
	"\x1eEnableIcalSubscriptionResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\" \n" +
	"\x1eDisableIcalSubscriptionRequest\"!\n" +
	"\x1fDisableIcalSubscriptionResponse2\x88\x03\n" +
	"\x0fCalendarService\x12|\n" +
	"\x16GetIcalSubscriptionUrl\x12*.calendar.v1.GetIcalSubscriptionUrlRequest\x1a+.calendar.v1.GetIcalSubscriptionUrlResponse\"\t\x82\xb5\x18\x02\b\x03\x90\x02\x01\x12y\n" +
	"\x16EnableIcalSubscription\x12*.calendar.v1.EnableIcalSubscriptionRequest\x1a+.calendar.v1.EnableIcalSubscriptionResponse\"\x06\x82\xb5\x18\x02\b\x03\x12|\n" +
	"\x17DisableIcalSubscription\x12+.calendar.v1.DisableIcalSubscriptionRequest\x1a,.calendar.v1.DisableIcalSubscriptionResponse\"\x06\x82\xb5\x18\x02\b\x03Bj\n" +
	"\x1anet.twinte.api.calendar.v1ZLgithub.com/twin-te/twin-te/back/handler/api/v4/rpcgen/calendar/v1;calendarv1b\x06proto3"

var (
	file_calendar_v1_service_proto_rawDescOnce sync.Once
	file_calendar_v1_service_proto_rawDescData []byte
)

func file_calendar_v1_service_proto_rawDescGZIP() []byte {
	file_calendar_v1_service_proto_rawDescOnce.Do(func() {
		file_calendar_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calendar_v1_service_proto_rawDesc), len(file_calendar_v1_service_proto_rawDesc)))
	})
	return file_calendar_v1_service_proto_rawDescData
}

var file_calendar_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_calendar_v1_service_proto_goTypes = []any{
	(*GetIcalSubscriptionUrlRequest)(nil),   // 0: calendar.v1.GetIcalSubscriptionUrlRequest
	(*GetIcalSubscriptionUrlResponse)(nil),  // 1: calendar.v1.GetIcalSubscriptionUrlResponse
	(*EnableIcalSubscriptionRequest)(nil),   // 2: calendar.v1.EnableIcalSubscriptionRequest
	(*EnableIcalSubscriptionResponse)(nil),  // 3: calendar.v1.EnableIcalSubscriptionResponse
	(*DisableIcalSubscriptionRequest)(nil),  // 4: calendar.v1.DisableIcalSubscriptionRequest
	(*DisableIcalSubscriptionResponse)(nil), // 5: calendar.v1.DisableIcalSubscriptionResponse
}
var file_calendar_v1_service_proto_depIdxs = []int32{
	0, // 0: calendar.v1.CalendarService.GetIcalSubscriptionUrl:input_type -> calendar.v1.GetIcalSubscriptionUrlRequest
	2, // 1: calendar.v1.CalendarService.EnableIcalSubscription:input_type -> calendar.v1.EnableIcalSubscriptionRequest
	4, // 2: calendar.v1.CalendarService.DisableIcalSubscription:input_type -> calendar.v1.DisableIcalSubscriptionRequest
	1, // 3: calendar.v1.CalendarService.GetIcalSubscriptionUrl:output_type -> calendar.v1.GetIcalSubscriptionUrlResponse
	3, // 4: calendar.v1.CalendarService.EnableIcalSubscription:output_type -> calendar.v1.EnableIcalSubscriptionResponse
	5, // 5: calendar.v1.CalendarService.DisableIcalSubscription:output_type -> calendar.v1.DisableIcalSubscriptionResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calendar_v1_service_proto_init() }
func file_calendar_v1_service_proto_init() {
	if File_calendar_v1_service_proto != nil {
		return
	}
	file_calendar_v1_service_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calendar_v1_service_proto_rawDesc), len(file_calendar_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calendar_v1_service_proto_goTypes,
		DependencyIndexes: file_calendar_v1_service_proto_depIdxs,
		MessageInfos:      file_calendar_v1_service_proto_msgTypes,
	}.Build()
	File_calendar_v1_service_proto = out.File
	file_calendar_v1_service_proto_goTypes = nil
	file_calendar_v1_service_proto_depIdxs = nil
}
