// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: shared/option.proto

package sharedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Authentication int32

const (
	Authentication_AUTHENTICATION_UNSPECIFIED Authentication = 0
	Authentication_NOT_REQURED                Authentication = 1
	Authentication_OPTIONAL                   Authentication = 2
	Authentication_REQURED                    Authentication = 3
)

// Enum value maps for Authentication.
var (
	Authentication_name = map[int32]string{
		0: "AUTHENTICATION_UNSPECIFIED",
		1: "NOT_REQURED",
		2: "OPTIONAL",
		3: "REQURED",
	}
	Authentication_value = map[string]int32{
		"AUTHENTICATION_UNSPECIFIED": 0,
		"NOT_REQURED":                1,
		"OPTIONAL":                   2,
		"REQURED":                    3,
	}
)

func (x Authentication) Enum() *Authentication {
	p := new(Authentication)
	*p = x
	return p
}

func (x Authentication) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Authentication) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_option_proto_enumTypes[0].Descriptor()
}

func (Authentication) Type() protoreflect.EnumType {
	return &file_shared_option_proto_enumTypes[0]
}

func (x Authentication) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Authentication.Descriptor instead.
func (Authentication) EnumDescriptor() ([]byte, []int) {
	return file_shared_option_proto_rawDescGZIP(), []int{0}
}

type TwinteMethodOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Authentication Authentication         `protobuf:"varint,1,opt,name=authentication,proto3,enum=shared.Authentication" json:"authentication,omitempty"`
	ErrorCodes     []string               `protobuf:"bytes,2,rep,name=error_codes,json=errorCodes,proto3" json:"error_codes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TwinteMethodOptions) Reset() {
	*x = TwinteMethodOptions{}
	mi := &file_shared_option_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwinteMethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwinteMethodOptions) ProtoMessage() {}

func (x *TwinteMethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_shared_option_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwinteMethodOptions.ProtoReflect.Descriptor instead.
func (*TwinteMethodOptions) Descriptor() ([]byte, []int) {
	return file_shared_option_proto_rawDescGZIP(), []int{0}
}

func (x *TwinteMethodOptions) GetAuthentication() Authentication {
	if x != nil {
		return x.Authentication
	}
	return Authentication_AUTHENTICATION_UNSPECIFIED
}

func (x *TwinteMethodOptions) GetErrorCodes() []string {
	if x != nil {
		return x.ErrorCodes
	}
	return nil
}

var file_shared_option_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*TwinteMethodOptions)(nil),
		Field:         50000,
		Name:          "shared.twinte",
		Tag:           "bytes,50000,opt,name=twinte",
		Filename:      "shared/option.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional shared.TwinteMethodOptions twinte = 50000;
	E_Twinte = &file_shared_option_proto_extTypes[0]
)

var File_shared_option_proto protoreflect.FileDescriptor

const file_shared_option_proto_rawDesc = "" +
	"\n" +
	"\x13shared/option.proto\x12\x06shared\x1a google/protobuf/descriptor.proto\"v\n" +
	"\x13TwinteMethodOptions\x12>\n" +
	"\x0eauthentication\x18\x01 \x01(\x0e2\x16.shared.AuthenticationR\x0eauthentication\x12\x1f\n" +
	"\verror_codes\x18\x02 \x03(\tR\n" +
	"errorCodes*\\\n" +
	"\x0eAuthentication\x12\x1e\n" +
	"\x1aAUTHENTICATION_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vNOT_REQURED\x10\x01\x12\f\n" +
	"\bOPTIONAL\x10\x02\x12\v\n" +
	"\aREQURED\x10\x03:U\n" +
	"\x06twinte\x12\x1e.google.protobuf.MethodOptions\x18І\x03 \x01(\v2\x1b.shared.TwinteMethodOptionsR\x06twinteBW\n" +
	"\x15net.twinte.api.sharedZ>github.com/twin-te/twin-te/back/handler/api/v4/rpcgen/sharedpbb\x06proto3"

var (
	file_shared_option_proto_rawDescOnce sync.Once
	file_shared_option_proto_rawDescData []byte
)

func file_shared_option_proto_rawDescGZIP() []byte {
	file_shared_option_proto_rawDescOnce.Do(func() {
		file_shared_option_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_option_proto_rawDesc), len(file_shared_option_proto_rawDesc)))
	})
	return file_shared_option_proto_rawDescData
}

var file_shared_option_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_option_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shared_option_proto_goTypes = []any{
	(Authentication)(0),                // 0: shared.Authentication
	(*TwinteMethodOptions)(nil),        // 1: shared.TwinteMethodOptions
	(*descriptorpb.MethodOptions)(nil), // 2: google.protobuf.MethodOptions
}
var file_shared_option_proto_depIdxs = []int32{
	0, // 0: shared.TwinteMethodOptions.authentication:type_name -> shared.Authentication
	2, // 1: shared.twinte:extendee -> google.protobuf.MethodOptions
	1, // 2: shared.twinte:type_name -> shared.TwinteMethodOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_option_proto_init() }
func file_shared_option_proto_init() {
	if File_shared_option_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_option_proto_rawDesc), len(file_shared_option_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_shared_option_proto_goTypes,
		DependencyIndexes: file_shared_option_proto_depIdxs,
		EnumInfos:         file_shared_option_proto_enumTypes,
		MessageInfos:      file_shared_option_proto_msgTypes,
		ExtensionInfos:    file_shared_option_proto_extTypes,
	}.Build()
	File_shared_option_proto = out.File
	file_shared_option_proto_goTypes = nil
	file_shared_option_proto_depIdxs = nil
}
