// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: shared/type.proto

package sharedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Weekday int32

const (
	Weekday_WEEKDAY_UNSPECIFIED Weekday = 0
	Weekday_WEEKDAY_SUNDAY      Weekday = 1
	Weekday_WEEKDAY_MONDAY      Weekday = 2
	Weekday_WEEKDAY_TUESDAY     Weekday = 3
	Weekday_WEEKDAY_WEDNESDAY   Weekday = 4
	Weekday_WEEKDAY_THURSDAY    Weekday = 5
	Weekday_WEEKDAY_FRIDAY      Weekday = 6
	Weekday_WEEKDAY_SATURDAY    Weekday = 7
)

// Enum value maps for Weekday.
var (
	Weekday_name = map[int32]string{
		0: "WEEKDAY_UNSPECIFIED",
		1: "WEEKDAY_SUNDAY",
		2: "WEEKDAY_MONDAY",
		3: "WEEKDAY_TUESDAY",
		4: "WEEKDAY_WEDNESDAY",
		5: "WEEKDAY_THURSDAY",
		6: "WEEKDAY_FRIDAY",
		7: "WEEKDAY_SATURDAY",
	}
	Weekday_value = map[string]int32{
		"WEEKDAY_UNSPECIFIED": 0,
		"WEEKDAY_SUNDAY":      1,
		"WEEKDAY_MONDAY":      2,
		"WEEKDAY_TUESDAY":     3,
		"WEEKDAY_WEDNESDAY":   4,
		"WEEKDAY_THURSDAY":    5,
		"WEEKDAY_FRIDAY":      6,
		"WEEKDAY_SATURDAY":    7,
	}
)

func (x Weekday) Enum() *Weekday {
	p := new(Weekday)
	*p = x
	return p
}

func (x Weekday) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Weekday) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_type_proto_enumTypes[0].Descriptor()
}

func (Weekday) Type() protoreflect.EnumType {
	return &file_shared_type_proto_enumTypes[0]
}

func (x Weekday) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Weekday.Descriptor instead.
func (Weekday) EnumDescriptor() ([]byte, []int) {
	return file_shared_type_proto_rawDescGZIP(), []int{0}
}

type OptionalString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalString) Reset() {
	*x = OptionalString{}
	mi := &file_shared_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalString) ProtoMessage() {}

func (x *OptionalString) ProtoReflect() protoreflect.Message {
	mi := &file_shared_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalString.ProtoReflect.Descriptor instead.
func (*OptionalString) Descriptor() ([]byte, []int) {
	return file_shared_type_proto_rawDescGZIP(), []int{0}
}

func (x *OptionalString) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type AcademicYear struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcademicYear) Reset() {
	*x = AcademicYear{}
	mi := &file_shared_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcademicYear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcademicYear) ProtoMessage() {}

func (x *AcademicYear) ProtoReflect() protoreflect.Message {
	mi := &file_shared_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcademicYear.ProtoReflect.Descriptor instead.
func (*AcademicYear) Descriptor() ([]byte, []int) {
	return file_shared_type_proto_rawDescGZIP(), []int{1}
}

func (x *AcademicYear) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_shared_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_shared_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_shared_type_proto_rawDescGZIP(), []int{2}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UUIDList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*UUID                `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUIDList) Reset() {
	*x = UUIDList{}
	mi := &file_shared_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUIDList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDList) ProtoMessage() {}

func (x *UUIDList) ProtoReflect() protoreflect.Message {
	mi := &file_shared_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDList.ProtoReflect.Descriptor instead.
func (*UUIDList) Descriptor() ([]byte, []int) {
	return file_shared_type_proto_rawDescGZIP(), []int{3}
}

func (x *UUIDList) GetValues() []*UUID {
	if x != nil {
		return x.Values
	}
	return nil
}

// e.g. 2006-01-02
type RFC3339FullDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RFC3339FullDate) Reset() {
	*x = RFC3339FullDate{}
	mi := &file_shared_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RFC3339FullDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RFC3339FullDate) ProtoMessage() {}

func (x *RFC3339FullDate) ProtoReflect() protoreflect.Message {
	mi := &file_shared_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RFC3339FullDate.ProtoReflect.Descriptor instead.
func (*RFC3339FullDate) Descriptor() ([]byte, []int) {
	return file_shared_type_proto_rawDescGZIP(), []int{4}
}

func (x *RFC3339FullDate) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// e.g. 2006-01-02T15:04:05.999999+09:00
type RFC3339DateTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RFC3339DateTime) Reset() {
	*x = RFC3339DateTime{}
	mi := &file_shared_type_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RFC3339DateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RFC3339DateTime) ProtoMessage() {}

func (x *RFC3339DateTime) ProtoReflect() protoreflect.Message {
	mi := &file_shared_type_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RFC3339DateTime.ProtoReflect.Descriptor instead.
func (*RFC3339DateTime) Descriptor() ([]byte, []int) {
	return file_shared_type_proto_rawDescGZIP(), []int{5}
}

func (x *RFC3339DateTime) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_shared_type_proto protoreflect.FileDescriptor

const file_shared_type_proto_rawDesc = "" +
	"\n" +
	"\x11shared/type.proto\x12\x06shared\"5\n" +
	"\x0eOptionalString\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"$\n" +
	"\fAcademicYear\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\"\x1c\n" +
	"\x04UUID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"0\n" +
	"\bUUIDList\x12$\n" +
	"\x06values\x18\x01 \x03(\v2\f.shared.UUIDR\x06values\"'\n" +
	"\x0fRFC3339FullDate\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"'\n" +
	"\x0fRFC3339DateTime\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value*\xb6\x01\n" +
	"\aWeekday\x12\x17\n" +
	"\x13WEEKDAY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eWEEKDAY_SUNDAY\x10\x01\x12\x12\n" +
	"\x0eWEEKDAY_MONDAY\x10\x02\x12\x13\n" +
	"\x0fWEEKDAY_TUESDAY\x10\x03\x12\x15\n" +
	"\x11WEEKDAY_WEDNESDAY\x10\x04\x12\x14\n" +
	"\x10WEEKDAY_THURSDAY\x10\x05\x12\x12\n" +
	"\x0eWEEKDAY_FRIDAY\x10\x06\x12\x14\n" +
	"\x10WEEKDAY_SATURDAY\x10\aBW\n" +
	"\x15net.twinte.api.sharedZ>github.com/twin-te/twin-te/back/handler/api/v4/rpcgen/sharedpbb\x06proto3"

var (
	file_shared_type_proto_rawDescOnce sync.Once
	file_shared_type_proto_rawDescData []byte
)

func file_shared_type_proto_rawDescGZIP() []byte {
	file_shared_type_proto_rawDescOnce.Do(func() {
		file_shared_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_type_proto_rawDesc), len(file_shared_type_proto_rawDesc)))
	})
	return file_shared_type_proto_rawDescData
}

var file_shared_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_type_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shared_type_proto_goTypes = []any{
	(Weekday)(0),            // 0: shared.Weekday
	(*OptionalString)(nil),  // 1: shared.OptionalString
	(*AcademicYear)(nil),    // 2: shared.AcademicYear
	(*UUID)(nil),            // 3: shared.UUID
	(*UUIDList)(nil),        // 4: shared.UUIDList
	(*RFC3339FullDate)(nil), // 5: shared.RFC3339FullDate
	(*RFC3339DateTime)(nil), // 6: shared.RFC3339DateTime
}
var file_shared_type_proto_depIdxs = []int32{
	3, // 0: shared.UUIDList.values:type_name -> shared.UUID
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_type_proto_init() }
func file_shared_type_proto_init() {
	if File_shared_type_proto != nil {
		return
	}
	file_shared_type_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_type_proto_rawDesc), len(file_shared_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_type_proto_goTypes,
		DependencyIndexes: file_shared_type_proto_depIdxs,
		EnumInfos:         file_shared_type_proto_enumTypes,
		MessageInfos:      file_shared_type_proto_msgTypes,
	}.Build()
	File_shared_type_proto = out.File
	file_shared_type_proto_goTypes = nil
	file_shared_type_proto_depIdxs = nil
}
