// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: schoolcalendar/v1/service.proto

package schoolcalendarv1

import (
	sharedpb "github.com/twin-te/twin-te/back/handler/api/v4/rpcgen/sharedpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListEventsByDateRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Date          *sharedpb.RFC3339FullDate `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsByDateRequest) Reset() {
	*x = ListEventsByDateRequest{}
	mi := &file_schoolcalendar_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsByDateRequest) ProtoMessage() {}

func (x *ListEventsByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schoolcalendar_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsByDateRequest.ProtoReflect.Descriptor instead.
func (*ListEventsByDateRequest) Descriptor() ([]byte, []int) {
	return file_schoolcalendar_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListEventsByDateRequest) GetDate() *sharedpb.RFC3339FullDate {
	if x != nil {
		return x.Date
	}
	return nil
}

type ListEventsByDateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsByDateResponse) Reset() {
	*x = ListEventsByDateResponse{}
	mi := &file_schoolcalendar_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsByDateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsByDateResponse) ProtoMessage() {}

func (x *ListEventsByDateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schoolcalendar_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsByDateResponse.ProtoReflect.Descriptor instead.
func (*ListEventsByDateResponse) Descriptor() ([]byte, []int) {
	return file_schoolcalendar_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListEventsByDateResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetModuleByDateRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Date          *sharedpb.RFC3339FullDate `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleByDateRequest) Reset() {
	*x = GetModuleByDateRequest{}
	mi := &file_schoolcalendar_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleByDateRequest) ProtoMessage() {}

func (x *GetModuleByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schoolcalendar_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleByDateRequest.ProtoReflect.Descriptor instead.
func (*GetModuleByDateRequest) Descriptor() ([]byte, []int) {
	return file_schoolcalendar_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetModuleByDateRequest) GetDate() *sharedpb.RFC3339FullDate {
	if x != nil {
		return x.Date
	}
	return nil
}

type GetModuleByDateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        Module                 `protobuf:"varint,1,opt,name=module,proto3,enum=schoolcalendar.v1.Module" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleByDateResponse) Reset() {
	*x = GetModuleByDateResponse{}
	mi := &file_schoolcalendar_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleByDateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleByDateResponse) ProtoMessage() {}

func (x *GetModuleByDateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schoolcalendar_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleByDateResponse.ProtoReflect.Descriptor instead.
func (*GetModuleByDateResponse) Descriptor() ([]byte, []int) {
	return file_schoolcalendar_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetModuleByDateResponse) GetModule() Module {
	if x != nil {
		return x.Module
	}
	return Module_MODULE_UNSPECIFIED
}

var File_schoolcalendar_v1_service_proto protoreflect.FileDescriptor

const file_schoolcalendar_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1fschoolcalendar/v1/service.proto\x12\x11schoolcalendar.v1\x1a\x1cschoolcalendar/v1/type.proto\x1a\x13shared/option.proto\x1a\x11shared/type.proto\"F\n" +
	"\x17ListEventsByDateRequest\x12+\n" +
	"\x04date\x18\x01 \x01(\v2\x17.shared.RFC3339FullDateR\x04date\"L\n" +
	"\x18ListEventsByDateResponse\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.schoolcalendar.v1.EventR\x06events\"E\n" +
	"\x16GetModuleByDateRequest\x12+\n" +
	"\x04date\x18\x01 \x01(\v2\x17.shared.RFC3339FullDateR\x04date\"L\n" +
	"\x17GetModuleByDateResponse\x121\n" +
	"\x06module\x18\x01 \x01(\x0e2\x19.schoolcalendar.v1.ModuleR\x06module2\xa4\x02\n" +
	"\x15SchoolCalendarService\x12v\n" +
	"\x10ListEventsByDate\x12*.schoolcalendar.v1.ListEventsByDateRequest\x1a+.schoolcalendar.v1.ListEventsByDateResponse\"\t\x82\xb5\x18\x02\b\x01\x90\x02\x01\x12\x92\x01\n" +
	"\x0fGetModuleByDate\x12).schoolcalendar.v1.GetModuleByDateRequest\x1a*.schoolcalendar.v1.GetModuleByDateResponse\"(\x82\xb5\x18!\b\x01\x12\x1dschoolcalendar.ModuleNotFound\x90\x02\x01B|\n" +
	" net.twinte.api.schoolcalendar.v1ZXgithub.com/twin-te/twin-te/back/handler/api/v4/rpcgen/schoolcalendar/v1;schoolcalendarv1b\x06proto3"

var (
	file_schoolcalendar_v1_service_proto_rawDescOnce sync.Once
	file_schoolcalendar_v1_service_proto_rawDescData []byte
)

func file_schoolcalendar_v1_service_proto_rawDescGZIP() []byte {
	file_schoolcalendar_v1_service_proto_rawDescOnce.Do(func() {
		file_schoolcalendar_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schoolcalendar_v1_service_proto_rawDesc), len(file_schoolcalendar_v1_service_proto_rawDesc)))
	})
	return file_schoolcalendar_v1_service_proto_rawDescData
}

var file_schoolcalendar_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_schoolcalendar_v1_service_proto_goTypes = []any{
	(*ListEventsByDateRequest)(nil),  // 0: schoolcalendar.v1.ListEventsByDateRequest
	(*ListEventsByDateResponse)(nil), // 1: schoolcalendar.v1.ListEventsByDateResponse
	(*GetModuleByDateRequest)(nil),   // 2: schoolcalendar.v1.GetModuleByDateRequest
	(*GetModuleByDateResponse)(nil),  // 3: schoolcalendar.v1.GetModuleByDateResponse
	(*sharedpb.RFC3339FullDate)(nil), // 4: shared.RFC3339FullDate
	(*Event)(nil),                    // 5: schoolcalendar.v1.Event
	(Module)(0),                      // 6: schoolcalendar.v1.Module
}
var file_schoolcalendar_v1_service_proto_depIdxs = []int32{
	4, // 0: schoolcalendar.v1.ListEventsByDateRequest.date:type_name -> shared.RFC3339FullDate
	5, // 1: schoolcalendar.v1.ListEventsByDateResponse.events:type_name -> schoolcalendar.v1.Event
	4, // 2: schoolcalendar.v1.GetModuleByDateRequest.date:type_name -> shared.RFC3339FullDate
	6, // 3: schoolcalendar.v1.GetModuleByDateResponse.module:type_name -> schoolcalendar.v1.Module
	0, // 4: schoolcalendar.v1.SchoolCalendarService.ListEventsByDate:input_type -> schoolcalendar.v1.ListEventsByDateRequest
	2, // 5: schoolcalendar.v1.SchoolCalendarService.GetModuleByDate:input_type -> schoolcalendar.v1.GetModuleByDateRequest
	1, // 6: schoolcalendar.v1.SchoolCalendarService.ListEventsByDate:output_type -> schoolcalendar.v1.ListEventsByDateResponse
	3, // 7: schoolcalendar.v1.SchoolCalendarService.GetModuleByDate:output_type -> schoolcalendar.v1.GetModuleByDateResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_schoolcalendar_v1_service_proto_init() }
func file_schoolcalendar_v1_service_proto_init() {
	if File_schoolcalendar_v1_service_proto != nil {
		return
	}
	file_schoolcalendar_v1_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schoolcalendar_v1_service_proto_rawDesc), len(file_schoolcalendar_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schoolcalendar_v1_service_proto_goTypes,
		DependencyIndexes: file_schoolcalendar_v1_service_proto_depIdxs,
		MessageInfos:      file_schoolcalendar_v1_service_proto_msgTypes,
	}.Build()
	File_schoolcalendar_v1_service_proto = out.File
	file_schoolcalendar_v1_service_proto_goTypes = nil
	file_schoolcalendar_v1_service_proto_depIdxs = nil
}
