// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: schoolcalendar/v1/type.proto

package schoolcalendarv1

import (
	sharedpb "github.com/twin-te/twin-te/back/handler/api/v4/rpcgen/sharedpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED    EventType = 0
	EventType_EVENT_TYPE_HOLIDAY        EventType = 1
	EventType_EVENT_TYPE_PUBLIC_HOLIDAY EventType = 2
	EventType_EVENT_TYPE_EXAM           EventType = 3
	EventType_EVENT_TYPE_SUBSTITUTE_DAY EventType = 4
	EventType_EVENT_TYPE_OTHER          EventType = 5
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_HOLIDAY",
		2: "EVENT_TYPE_PUBLIC_HOLIDAY",
		3: "EVENT_TYPE_EXAM",
		4: "EVENT_TYPE_SUBSTITUTE_DAY",
		5: "EVENT_TYPE_OTHER",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":    0,
		"EVENT_TYPE_HOLIDAY":        1,
		"EVENT_TYPE_PUBLIC_HOLIDAY": 2,
		"EVENT_TYPE_EXAM":           3,
		"EVENT_TYPE_SUBSTITUTE_DAY": 4,
		"EVENT_TYPE_OTHER":          5,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_schoolcalendar_v1_type_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_schoolcalendar_v1_type_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_schoolcalendar_v1_type_proto_rawDescGZIP(), []int{0}
}

type Module int32

const (
	Module_MODULE_UNSPECIFIED     Module = 0
	Module_MODULE_SPRING_A        Module = 1
	Module_MODULE_SPRING_B        Module = 2
	Module_MODULE_SPRING_C        Module = 3
	Module_MODULE_SUMMER_VACATION Module = 4
	Module_MODULE_FALL_A          Module = 5
	Module_MODULE_FALL_B          Module = 6
	Module_MODULE_WINTER_VACATION Module = 7
	Module_MODULE_FALL_C          Module = 8
	Module_MODULE_SPRING_VACATION Module = 9
)

// Enum value maps for Module.
var (
	Module_name = map[int32]string{
		0: "MODULE_UNSPECIFIED",
		1: "MODULE_SPRING_A",
		2: "MODULE_SPRING_B",
		3: "MODULE_SPRING_C",
		4: "MODULE_SUMMER_VACATION",
		5: "MODULE_FALL_A",
		6: "MODULE_FALL_B",
		7: "MODULE_WINTER_VACATION",
		8: "MODULE_FALL_C",
		9: "MODULE_SPRING_VACATION",
	}
	Module_value = map[string]int32{
		"MODULE_UNSPECIFIED":     0,
		"MODULE_SPRING_A":        1,
		"MODULE_SPRING_B":        2,
		"MODULE_SPRING_C":        3,
		"MODULE_SUMMER_VACATION": 4,
		"MODULE_FALL_A":          5,
		"MODULE_FALL_B":          6,
		"MODULE_WINTER_VACATION": 7,
		"MODULE_FALL_C":          8,
		"MODULE_SPRING_VACATION": 9,
	}
)

func (x Module) Enum() *Module {
	p := new(Module)
	*p = x
	return p
}

func (x Module) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Module) Descriptor() protoreflect.EnumDescriptor {
	return file_schoolcalendar_v1_type_proto_enumTypes[1].Descriptor()
}

func (Module) Type() protoreflect.EnumType {
	return &file_schoolcalendar_v1_type_proto_enumTypes[1]
}

func (x Module) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Module.Descriptor instead.
func (Module) EnumDescriptor() ([]byte, []int) {
	return file_schoolcalendar_v1_type_proto_rawDescGZIP(), []int{1}
}

type Event struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            int32                     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          EventType                 `protobuf:"varint,2,opt,name=type,proto3,enum=schoolcalendar.v1.EventType" json:"type,omitempty"`
	Date          *sharedpb.RFC3339FullDate `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Description   string                    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ChangeTo      *sharedpb.Weekday         `protobuf:"varint,5,opt,name=change_to,json=changeTo,proto3,enum=shared.Weekday,oneof" json:"change_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_schoolcalendar_v1_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_schoolcalendar_v1_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_schoolcalendar_v1_type_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetDate() *sharedpb.RFC3339FullDate {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetChangeTo() sharedpb.Weekday {
	if x != nil && x.ChangeTo != nil {
		return *x.ChangeTo
	}
	return sharedpb.Weekday(0)
}

var File_schoolcalendar_v1_type_proto protoreflect.FileDescriptor

const file_schoolcalendar_v1_type_proto_rawDesc = "" +
	"\n" +
	"\x1cschoolcalendar/v1/type.proto\x12\x11schoolcalendar.v1\x1a\x11shared/type.proto\"\xd9\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.schoolcalendar.v1.EventTypeR\x04type\x12+\n" +
	"\x04date\x18\x03 \x01(\v2\x17.shared.RFC3339FullDateR\x04date\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x121\n" +
	"\tchange_to\x18\x05 \x01(\x0e2\x0f.shared.WeekdayH\x00R\bchangeTo\x88\x01\x01B\f\n" +
	"\n" +
	"_change_to*\xa8\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_HOLIDAY\x10\x01\x12\x1d\n" +
	"\x19EVENT_TYPE_PUBLIC_HOLIDAY\x10\x02\x12\x13\n" +
	"\x0fEVENT_TYPE_EXAM\x10\x03\x12\x1d\n" +
	"\x19EVENT_TYPE_SUBSTITUTE_DAY\x10\x04\x12\x14\n" +
	"\x10EVENT_TYPE_OTHER\x10\x05*\xec\x01\n" +
	"\x06Module\x12\x16\n" +
	"\x12MODULE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fMODULE_SPRING_A\x10\x01\x12\x13\n" +
	"\x0fMODULE_SPRING_B\x10\x02\x12\x13\n" +
	"\x0fMODULE_SPRING_C\x10\x03\x12\x1a\n" +
	"\x16MODULE_SUMMER_VACATION\x10\x04\x12\x11\n" +
	"\rMODULE_FALL_A\x10\x05\x12\x11\n" +
	"\rMODULE_FALL_B\x10\x06\x12\x1a\n" +
	"\x16MODULE_WINTER_VACATION\x10\a\x12\x11\n" +
	"\rMODULE_FALL_C\x10\b\x12\x1a\n" +
	"\x16MODULE_SPRING_VACATION\x10\tB|\n" +
	" net.twinte.api.schoolcalendar.v1ZXgithub.com/twin-te/twin-te/back/handler/api/v4/rpcgen/schoolcalendar/v1;schoolcalendarv1b\x06proto3"

var (
	file_schoolcalendar_v1_type_proto_rawDescOnce sync.Once
	file_schoolcalendar_v1_type_proto_rawDescData []byte
)

func file_schoolcalendar_v1_type_proto_rawDescGZIP() []byte {
	file_schoolcalendar_v1_type_proto_rawDescOnce.Do(func() {
		file_schoolcalendar_v1_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schoolcalendar_v1_type_proto_rawDesc), len(file_schoolcalendar_v1_type_proto_rawDesc)))
	})
	return file_schoolcalendar_v1_type_proto_rawDescData
}

var file_schoolcalendar_v1_type_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_schoolcalendar_v1_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schoolcalendar_v1_type_proto_goTypes = []any{
	(EventType)(0),                   // 0: schoolcalendar.v1.EventType
	(Module)(0),                      // 1: schoolcalendar.v1.Module
	(*Event)(nil),                    // 2: schoolcalendar.v1.Event
	(*sharedpb.RFC3339FullDate)(nil), // 3: shared.RFC3339FullDate
	(sharedpb.Weekday)(0),            // 4: shared.Weekday
}
var file_schoolcalendar_v1_type_proto_depIdxs = []int32{
	0, // 0: schoolcalendar.v1.Event.type:type_name -> schoolcalendar.v1.EventType
	3, // 1: schoolcalendar.v1.Event.date:type_name -> shared.RFC3339FullDate
	4, // 2: schoolcalendar.v1.Event.change_to:type_name -> shared.Weekday
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_schoolcalendar_v1_type_proto_init() }
func file_schoolcalendar_v1_type_proto_init() {
	if File_schoolcalendar_v1_type_proto != nil {
		return
	}
	file_schoolcalendar_v1_type_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schoolcalendar_v1_type_proto_rawDesc), len(file_schoolcalendar_v1_type_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schoolcalendar_v1_type_proto_goTypes,
		DependencyIndexes: file_schoolcalendar_v1_type_proto_depIdxs,
		EnumInfos:         file_schoolcalendar_v1_type_proto_enumTypes,
		MessageInfos:      file_schoolcalendar_v1_type_proto_msgTypes,
	}.Build()
	File_schoolcalendar_v1_type_proto = out.File
	file_schoolcalendar_v1_type_proto_goTypes = nil
	file_schoolcalendar_v1_type_proto_depIdxs = nil
}
