name: CI(front)
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: ./front

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          CI: true

      - name: Format
        run: bun run format
        env:
          CI: true

      - name: Lint
        run: bun run lint
        env:
          CI: true

      - name: Test
        run: bun run test --ci --coverage --maxWorkers=2
        env:
          CI: true

      - name: Build
        run: bun run build
        env:
          CI: true
