name: CI (parser)

on:
  push:
    paths:
      - "parser/**"
      - ".github/workflows/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Build and Run Snapshot Tests
        run: docker compose run -T --build --rm parser uv run ./snapshot_test.py
