name: Build and Push Frontend Image
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
    secrets:
      sentry_auth_token:
        required: false
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: front
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: cache-mount
          key: cache-mount-front-${{ hashFiles('front/Dockerfile') }}
      - name: Restore Docker cache mounts
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-dir: cache-mount
          dockerfile: front/Dockerfile
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: front
          target: ${{ inputs.target }}
          push: true
          tags: ghcr.io/twin-te/twin-te:front-${{ inputs.target }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            "SENTRY_AUTH_TOKEN=${{ secrets.sentry_auth_token }}"
